cpputest/cpputest

Makefile.am
src/Platforms/Gcc/UtestPlatform.cpp

Test for -p option

---

CppUTest.vcxproj

Fix crashes of VS2010 Release executable

---

tests/SetPluginTest.cpp

This fixes the ignored test I found in issue #461.  It also looked like the other tests in that file weren't working correctly, but weren't failing either, so I added some extra checks to them and then fixed them.

Fixed ignored test in SetPluginTest.cpp

---

include/CppUTestExt/MockSupport.h
src/CppUTestExt/MockSupport.cpp
tests/CppUTestExt/MockSupportTest.cpp

Fix strict order problem with mock scopes

---

tests/SetPluginTest.cpp
tests/UtestTest.cpp

Couldn't live with the original test :-)

1. refactor: Fix and simplify misplaced test

---

src/Platforms/VisualCpp/UtestPlatform.cpp
tests/AllTests.vcxproj
tests/UtestPlatformTest.cpp
tests/UtestTest.cpp

Some changes were made for MinGW, also marked those changes to apply to Visual C++

Fixes to visual c++ for #492

---

src/Platforms/VisualCpp/UtestPlatform.cpp

This is a possible solution for #482.

Add wrappers for MSVC secure functions

---

CppUTest.dsp
CppUTest.dsw

As discussed on https://github.com/PaulBussmann/cpputest/commit/2a6521c1f173695204823d9189162430e9281878

Removed non-existing AllTests.dsp from CppUTest.dsw and Added unreferenced cpp-files needed to build cpputest.lib

---

CppUTest.dsw
CppUTest.mak
tests/AllTests.dep
tests/AllTests.dsp
tests/AllTests.mak

Must have been over-zealous :-(

Put back vc6 files

---

CppUTest.dsp
src/CppUTest/MemoryLeakDetector.cpp
src/CppUTestExt/MockExpectedCall.cpp
src/CppUTestExt/MockSupport_c.cpp
tests/AllTests.dsp

AllTests.dsp to follow soon.
Tested by successful import into VC2005 & successful compile.
This grew quite a bit because errors had to be fixed resulting from adding all the tests and CppUTestExt sources.

CppUTest.dsp revamped

---

src/CppUTest/SimpleString.cpp
tests/SimpleStringTest.cpp

Additional tests and a small fix for SimpleString

Simplestring

---

include/CppUTest/TestRegistry.h
src/CppUTest/TestRegistry.cpp
tests/TestRegistryTest.cpp

Increasing statement coverage to 100%

Testregistry

---

tests/AllTests.dsp

Fix the real cause of the CppUTestExt problems with VC6

Use the AllTests.cpp from tests/CppUTestExt/

---

CppUTest.mak
tests/AllTests.dep
tests/AllTests.dsp
tests/AllTests.mak

Vc6final - Fix Release configuration and re-generate .mak/.dep

---

include/CppUTest/MemoryLeakDetector.h
src/CppUTest/MemoryLeakDetector.cpp

Towards 100% Coverage for MemoryLeakDetector.cpp

---

include/CppUTest/MemoryLeakDetector.h
src/CppUTest/MemoryLeakDetector.cpp
tests/MemoryLeakDetectorTest.cpp

Towards 100% Coverage for MemoryLeakDetector.cpp (2 of 2)

---

include/CppUTestExt/CodeMemoryReportFormatter.h
include/CppUTestExt/MemoryReportFormatter.h
tests/CppUTestExt/MockSupport_cTestCFile.c

This goes after the JUnitOutput one.

Misc - Lcov Exclusions and white space

---

include/CppUTest/PlatformSpecificFunctions_c.h
src/Platforms/C2000/UtestPlatform.cpp
src/Platforms/Gcc/UtestPlatform.cpp
src/Platforms/GccNoStdC/UtestPlatform.cpp
src/Platforms/VisualCpp/UtestPlatform.cpp
tests/JUnitOutputTest.cpp

Which means, simultaneously, 100% coverage for all of src/Cpputest/ :-)

juo - 100% Coverage for JUnitTestOutput

---

include/CppUTest/PlatformSpecificFunctions_c.h
src/Platforms/C2000/UtestPlatform.cpp
src/Platforms/Gcc/UtestPlatform.cpp
src/Platforms/GccNoStdC/UtestPlatform.cpp
src/Platforms/VisualCpp/UtestPlatform.cpp

I really needed only a few but it's tiring to continue changing these files, since there's always a whole bunch to work on.
So I did the lot. I also dug out the old cl2000 compiler while I still have access to it and found a few things that need fixing (for another pull request)
This will help to test the remainder of JUnitOutput, among other things.

fp - Function Pointer Based Interface For All Platform-Specific Functions

---

include/CppUTestExt/MockSupport.h
src/CppUTestExt/MockSupport.cpp
tests/CppUTestExt/MockSupportTest.cpp

Count mock expectations as checks

---

include/CppUTest/Utest.h
include/CppUTest/UtestMacros.h
include/CppUTestExt/MockSupport.h
src/CppUTest/Utest.cpp
src/CppUTestExt/MockSupport.cpp

I like this one better; take your pick :-)

Alternate way of handling counting expectations

---

include/CppUTestExt/MockSupport_c.h
src/CppUTestExt/MockSupport_c.cpp
tests/CppUTestExt/MockSupport_cTest.cpp

Add crashOnFailure_c() interface and test crashing on failure with mock_c().

100% Coverage For MockSupport_c - Part 3 of 3

---

include/CppUTest/CommandLineTestRunner.h
src/CppUTest/CommandLineTestRunner.cpp
tests/CommandLineTestRunnerTest.cpp

Small refactoring to allow for pulling out the ConsoleOutput further.

Refactored CommandLineRunner to allow for new TestOutput

---

appveyor.yml
scripts/appveyor_ci_build.ps1
scripts/appveyor_ci_test.ps1

Here are the appveyor.yml and some build script files that it uses.  This will fail on AppVeyor unless some changes are made to the Visual Studio project files, but I figured those needed to be discussed a bit yet and should be a separate pull request.

Files to support AppVeyor

---

include/CppUTest/TestOutput.h
src/CppUTest/TestOutput.cpp
tests/TestOutputTest.cpp

Merged the Composite in the existing header and source. Also added some functionality.

Composite Test Output

---

tests/TestOutputTest.cpp

Fixed what @arstrube mentioned in his comment to the previous pull request.

Fixed Windows environment output difference

---

include/CppUTest/CommandLineTestRunner.h
src/CppUTest/CommandLineTestRunner.cpp
tests/CommandLineTestRunnerTest.cpp

Step #3 of getting verbose and JUnitOutput without ever touching the JUnitOutput class.

Verbose and JUnit

---

.gitignore
CppUTest.vcproj
CppUTest.vcxproj
appveyor.yml
scripts/appveyor_ci_test.ps1
tests/AllTests.vcproj
tests/AllTests.vcxproj

Please do not merge until I say so, still need to make changes and want to see if appveyor is handling the pull requests.
I still need to make some changes to VS2008 to match, but this should fix the VS2010 build at least.

Cleaned up the project output folders

---

platforms_examples/armcc/LPC1768/tests/main.cpp
platforms_examples/armcc/LPC1833/tests/test1.cpp
platforms_startup/armcc/LPC1833/Makefile
src/Platforms/armcc/UtestPlatform.cpp

Hello.
Here is working LPC1833 project to test in hardware (Cortex-M3 chip). Other projects for chips (AT91SAM7A3, LPC1768) also compiling, but I don't test them in hardware.
I make corrections to ARMCC port.

Correction for ARM C/C++ compiler to working with latest CppUTest

---

src/Platforms/Gcc/UtestPlatform.cpp

Fixes #628 
Note I didn't have a chance to run this past MinGW

Correct handling of __MinGW__ in Gcc/UtestPlatform.cpp

---

appveyor.yml
scripts/appveyor_ci_build.ps1
scripts/appveyor_ci_test.ps1

Added support for running the MinGW builds on Appveyor using CMake.
Is there a desire to include autotools as well?  Based on other comments I think that AppVeyor includes msys and could like do it, if people think that it would be helpful.

Appveyor mingw - CMake

---

appveyor.yml
scripts/appveyor_ci_build.ps1
scripts/appveyor_ci_test.ps1

I've added support to appveyor so that it runs MinGW as both a 32-bit and 64-bit build.

Appveyor multiplatform

---

src/CppUTest/TestRegistry.cpp
tests/TestRegistryTest.cpp

Replace comment by verbose test names. Includes PR #642 by @mmidor.

Fix test groups listing feature

---

CMakeLists.txt
Makefile.am
configure.ac

Added extra check to ensure no mistakes on OSX packaging.

---

tests/CppUTestExt/MockExpectedCallTest.cpp

Fixed build with GCC 5 (issue  #661)

---

src/Platforms/Gcc/UtestPlatform.cpp
src/Platforms/Iar/UtestPlatform.cpp
src/Platforms/VisualCpp/UtestPlatform.cpp
tests/UtestPlatformTest.cpp

@imr I hope the #define for IAR (`__IAR_SYSTEMS_ICC__`) hits the mark.
Please, let us know when this compiles and tests correctly on your system!

Fix UtestPlatform.cpp plus tests for IAR

---

Makefile.am
include/CppUTestExt/MockNamedValue.h
include/CppUTestExt/MockSupport.h
include/CppUTestExt/MockSupportPlugin.h
src/CppUTestExt/MockNamedValue.cpp
src/CppUTestExt/MockSupport.cpp
src/CppUTestExt/MockSupportPlugin.cpp
tests/CppUTestExt/MockExpectedCallTest.cpp
tests/CppUTestExt/MockNamedValueTest.cpp
tests/CppUTestExt/MockSupportTest.cpp

This is an example of how you can implement the repository. Not done yet.

Demo - Stupid repository implementation

---

Makefile.am
include/CppUTestExt/MockNamedValue.h
include/CppUTestExt/MockSupport.h
include/CppUTestExt/MockSupportPlugin.h
src/CppUTestExt/MockNamedValue.cpp
src/CppUTestExt/MockSupport.cpp
src/CppUTestExt/MockSupportPlugin.cpp
tests/CppUTestExt/MockExpectedCallTest.cpp
tests/CppUTestExt/MockNamedValueTest.cpp
tests/CppUTestExt/MockSupportTest.cpp

Copiers one list

---

include/CppUTestExt/MockFailure.h
include/CppUTestExt/MockNamedValue.h
src/CppUTestExt/MockFailure.cpp
src/CppUTestExt/MockNamedValue.cpp
tests/CppUTestExt/MockFailureTest.cpp

For review. This should be quite "digestable"
It does contain the renaming of the comment.... ah well, can rename it back later...

Copiers one list 2

---

src/Platforms/armcc/UtestPlatform.cpp
tests/UtestPlatformTest.cpp

Awaiting feedback... from Ivan Zrno
1. Added missing fp interfaces
2. Fixed somethings so they work with Keil on Arm
3. Fixed the order of everything, so its easier to compare to the other platform-specific versions (sorry, makes the PR a little more messy than need be)

Update ArmCC platform-specific Code

---

examples/AllTests/EventDispatcherTest.cpp
examples/AllTests/MockDocumentationTest.cpp
include/CppUTestExt/MockActualCall.h
include/CppUTestExt/MockCheckedActualCall.h
include/CppUTestExt/MockCheckedExpectedCall.h
include/CppUTestExt/MockExpectedCall.h
include/CppUTestExt/MockExpectedCallsList.h
include/CppUTestExt/MockSupport.h
include/CppUTestExt/MockSupportPlugin.h
include/CppUTestExt/MockSupport_c.h
src/CppUTestExt/MockActualCall.cpp
src/CppUTestExt/MockExpectedCall.cpp
src/CppUTestExt/MockExpectedCallsList.cpp
src/CppUTestExt/MockSupport.cpp
src/CppUTestExt/MockSupportPlugin.cpp
src/CppUTestExt/MockSupport_c.cpp
tests/CppUTestExt/MockExpectedCallTest.cpp
tests/CppUTestExt/MockPluginTest.cpp
tests/CppUTestExt/MockSupportTest.cpp
tests/CppUTestExt/MockSupport_cTest.cpp
tests/CppUTestExt/MockSupport_cTestCFile.c

Here is "the rest". We make have to break it down....

Copiers one list 3

---

include/CppUTestExt/MockNamedValue.h
tests/AllTests.dsp
tests/CppUTestExt/CMakeLists.txt
tests/CppUTestExt/MockNamedValueTest.cpp

Also fix an old error -- CppUTestd.lib should be linked with the Debug configuration.

Add MockNamedValueTest.cpp to AllTests.dsp (Visual C++ 6.0) 

---

CppUTest.vcxproj
include/CppUTestExt/MockNamedValue.h
tests/AllTests.dsp
tests/AllTests.vcxproj
tests/CppUTestExt/CMakeLists.txt
tests/CppUTestExt/MockNamedValueTest.cpp

Add MockNamedValueTest.cpp to AllTests.vcxproj

---

src/Platforms/Gcc/UtestPlatform.cpp

Fix for compilation errors related to isinf()

---

tests/TestFailureNaNTest.cpp

Missing override added

---

examples/AllTests/MockDocumentationTest.cpp
include/CppUTestExt/MockSupport_c.h
tests/CppUTestExt/MockSupport_cTest.cpp
tests/CppUTestExt/MockSupport_cTestCFile.c

Fix the const char * thing (again?)

---

src/Platforms/Dos/UtestPlatform.cpp

In preparation for a Open Watcom C / DOSBox target.
This has actually been tested offline to work with Open Watcom C/C++ and DOSBox.

Add Dos/UtestPlatform.cpp

---

tests/CppUTestExt/MockFailureTest.h
tests/CppUTestExt/MockSupportTest.cpp

Now it'll be easier to split. Needs to be shrinked more still.

Simplified MockSupportTest fixture in preparation for splitting

---

CMakeLists.txt
src/Platforms/Gcc/UtestPlatform.cpp
tests/UtestPlatformTest.cpp
tests/UtestTest.cpp

After a lot of trial and error, finally I got the check for fork() to work.

Use HAVE_FORK

---

tests/CppUTestExt/MockCallTest.cpp
tests/CppUTestExt/MockComparatorCopierTest.cpp
tests/CppUTestExt/MockParameterTest.cpp
tests/CppUTestExt/MockReturnValueTest.cpp
tests/CppUTestExt/MockSupportTest.cpp

Pulled out some more

---

.travis.yml
scripts/travis_ci_build.sh

First attempt to add more stuff to the build matrix.

Added additional stuff to the build matrix

---

src/Platforms/Dos/UtestPlatform.cpp

and clean up Dos/UtestPlatform.cpp

Dos build: Remove 2 compiler warnings

---

tests/CppUTestExt/MockSupportTest.cpp

Got rid of ORDERED_TEST

---

include/CppUTest/TestMemoryAllocator.h
src/CppUTest/TestMemoryAllocator.cpp
tests/TestMemoryAllocatorTest.cpp

Proposed. A simpler implementation. @jkohvakk I do think we lack some tests though, but not sure, I just refactored the implementation.

Different implementation of the Failable Allocator

---

scripts/appveyor_ci_build.ps1

Fixes https://github.com/cpputest/cpputest/issues/794

Remove 'C:\Program Files\Git\usr\bin' from the path, fix AppVeyor.

---

src/CppUTestExt/MockSupportPlugin.cpp
tests/CppUTestExt/MockPluginTest.cpp
tests/MemoryLeakDetectorTest.cpp

Please merge the multiple failure fix first

Fix Issue #798

---

src/CppUTestExt/MockSupportPlugin.cpp
tests/CppUTestExt/MockPluginTest.cpp

Fix multiple failures per test case.

---

tests/CppUTestExt/MemoryReportFormatterTest.cpp

Added two casts for clang3.7 warnings

---

src/CppUTestExt/MemoryReportFormatter.cpp
tests/TestMemoryAllocatorTest.cpp

Removed a few more warnings

---

.travis.yml

Here's my solution with just includes, I think it's easier to read than the one with excludes.  Your choice which one you like better though.

Travis.yml updates to use includes only

---

CppUTest.dsp
tests/AllTests.dsp
tests/CppUTestExt/MockFailureTest.h

I don't really like this fix, but I dislike the alternatives even more.

Fix broken VC6 test; add missing files to projects

---

include/CppUTest/SimpleString.h
src/CppUTest/SimpleString.cpp
src/Platforms/VisualCpp/UtestPlatform.cpp
tests/UtestPlatformTest.cpp

Fix for issue  #831

---

src/CppUTestExt/MockSupport.cpp
tests/CppUTestExt/MockStrictOrderTest.cpp

First commit, manipulate some tests to provoke the problem & failure.
Second commit, proposed fix.

Fix for issue #829

---

.travis.yml
scripts/travis_ci_build.sh

With this PR, we'd be using the new, container-based infrastructure on Travis CI.
Is that cool, or is that cool?

Dosbox has been white-listed

---

Makefile.am
examples/AllTests/FEDemoTest.cpp
include/CppUTest/CppUTestConfig.h
include/CppUTestExt/IEEE754ExceptionsPlugin.h
platforms/Dos/sources.mk
src/CppUTestExt/CMakeLists.txt
src/CppUTestExt/IEEE754ExceptionsPlugin.cpp
tests/CppUTestExt/CMakeLists.txt
tests/CppUTestExt/IEEE754PluginTest.cpp
tests/CppUTestExt/IEEE754PluginTest_c.c
tests/CppUTestExt/IEEE754PluginTest_c.h

 IEEE754 Floating Point Exception Flags Plugin

---

include/CppUTestExt/MockCheckedActualCall.h
tests/CppUTestExt/MockActualCallTest.cpp

Fix default return value of ignored actual calls

---

src/Platforms/Gcc/UtestPlatform.cpp

See #872.
Also tested with current GCC / Clang on linux.

Gcc fix for #872

---

src/CppUTest/Utest.cpp
tests/CppUTestExt/MockSupportTest.cpp

This fixes the bug that issue #879 describes

Fix for Issue #879

---

tests/SimpleStringTest.cpp
tests/TestFailureTest.cpp

It appears that conditional tests are no longer needed.

Apparently no longer necessary anymore for 16 bit Cl2000 or Dos

---

tests/CppUTestExt/MockSupport_cTest.cpp

Changed the values to functions to avoid casts

Changed values to real functions to get rid of warnings

---

src/Platforms/Gcc/UtestPlatform.cpp

@bukulin, @offa - this seems to work for all situations.....

GCC Float conversion fix (#871); separate version checks for Gcc

---

include/CppUTest/Utest.h
src/CppUTest/Utest.cpp

Updated the function pointer assertion with the new(ish) testTerminator parameter.

Add testTerminator parameter to function pointer assertion

---

examples/AllTests/AllTests.cpp
include/CppUTest/Utest.h
include/CppUTestExt/MockExpectedCallsList.h
include/CppUTestExt/MockSupport.h
include/Platforms/c2000/stdint.h
src/CppUTest/SimpleMutex.cpp
src/CppUTest/Utest.cpp
src/CppUTestExt/MockSupport.cpp
src/Platforms/Keil/UtestPlatform.cpp
src/Platforms/Symbian/README_Symbian.txt
src/Platforms/Symbian/SymbianMemoryLeakWarning.cpp
src/Platforms/Symbian/UtestPlatform.cpp
tests/CommandLineTestRunnerTest.cpp
tests/CppUTestExt/MockCallTest.cpp
tests/CppUTestExt/MockStrictOrderTest.cpp
tests/SimpleMutexTest.cpp
tests/TestUTestMacro.cpp

Remove trailing whitespace

---

examples/AllTests/FEDemoTest.cpp

Use -ri option rather than ugly #ifdef

---

tests/CppUTestExt/MockSupport_cTestCFile.c

Fix two warnings that breaks MSVC builds.

Msvc fix warnings

---

README_InstallCppUTest.txt
scripts/README.txt

Hi,
I followed README files to install scripts, but it seems it doesn't work correctly.
I think these READMEs should be updated.
Could you please review them?

Update READMEs to make InstallScript.sh working

---

include/CppUTest/CppUTestConfig.h
include/CppUTest/StandardCLibrary.h

And moved it up in the CppUtestConfig.h

Moved limits.h into StandardC.h

---

configure.ac

Small additions to configure.ac

Need -Werror for flag checking

---

examples/AllTests/FEDemoTest.cpp

Remove compile error for MacOSX

---

cmake/Modules/CppUTestWarningFlags.cmake

Changed the compiler flag checking for C++11. Not have much CMake experience, so not sure this will work :)

Refactored the C++ warning flag checking

---

include/CppUTest/TestHarness_c.h
src/CppUTest/TestHarness_c.cpp
tests/TestHarness_cTest.cpp

Continuing in the footsteps of the previous bool PRs...

Adds CHECK_EQUAL_C_BOOL to C TestHarness.

---

Makefile.am
configure.ac

Fixing the gtest build and providing support for gtest18

---

cmake/Modules/CppUTestConfigurationOptions.cmake
scripts/travis_ci_build.sh

Attempt to fix the CMake gtest build

Fixed CMake gtest build?

---

include/CppUTestExt/MockCheckedActualCall.h
tests/CppUTestExt/MockActualCallTest.cpp

Mock function returnBoolValueOrDefault behaves not as expected #1052

---

.travis.yml
scripts/travis_ci_after.sh
scripts/travis_ci_build.sh

Now it is right.
Build will fail in two mac builds, without the IEEE fix.

Added mac builds on travis

---

src/CppUTest/JUnitTestOutput.cpp
tests/CppUTest/JUnitOutputTest.cpp

Hello,
Is this a plausible solution to #33? As this is my first contribution to this project I would welcome your feedback and comments.
Cheers,
David

collect UT_PRINT() output in JUnit output file

---

CMakeLists.txt
src/CppUTest/CMakeLists.txt

Fixing cmake_minimum_version to 3.1 as target_sources requires it

---

src/CppUTest/CMakeLists.txt
src/CppUTestExt/CMakeLists.txt

Fixes #1203 
Signed-off-by: Avraham Shukron <avraham.shukron@gmail.com>

Add public headers as an exported properties of the library

---

scripts/travis_ci_build.sh

The coverage build options where screwed up.

CI coverage build option fixed

---

include/CppUTest/StandardCLibrary.h

Added this anyways and hope the nullptr problems will stay away

Added csdtdef for std::nulptr

---

README.md

Because I used this regularly and always forgot how to do it right. And also because googletest has something similar ;)

Added installation as external cmake project to README

---

include/CppUTest/TestOutput.h
include/CppUTest/Utest.h
include/CppUTestExt/MockFailure.h
include/CppUTestExt/OrderedTest.h
src/CppUTest/MemoryLeakWarningPlugin.cpp
src/CppUTest/Utest.cpp
src/CppUTestExt/MockFailure.cpp
tests/CppUTest/CommandLineArgumentsTest.cpp
tests/CppUTest/MemoryLeakDetectorTest.cpp
tests/CppUTest/MemoryLeakWarningTest.cpp
tests/CppUTest/SimpleStringTest.cpp
tests/CppUTest/TestRegistryTest.cpp
tests/CppUTestExt/MockFailureReporterForTest.h

Tired of these warnings showing up when I compile my code. :smiley:

Fix remaining missing class member function override specifiers

---

include/CppUTest/CommandLineArguments.h
include/CppUTest/PlatformSpecificFunctions_c.h
include/CppUTest/Shuffle.h
include/CppUTest/TestOutput.h
include/CppUTest/TestRegistry.h
src/CppUTest/CommandLineArguments.cpp
src/CppUTest/CommandLineTestRunner.cpp
src/CppUTest/TestOutput.cpp
src/CppUTest/TestRegistry.cpp
src/Platforms/Gcc/UtestPlatform.cpp
src/Platforms/VisualCpp/UtestPlatform.cpp
tests/CppUTest/CommandLineArgumentsTest.cpp
tests/CppUTest/CommandLineTestRunnerTest.cpp
tests/CppUTest/ShuffleTest.cpp
tests/CppUTest/TestRegistryTest.cpp

Cleaned up the shuffle feature and moved the platform dependent functions out. They should have never been in there. Need to pay better attention.

Removed the rand and srand out of shuffle and cleaned up the feature

---

include/CppUTest/CommandLineArguments.h
src/CppUTest/CommandLineArguments.cpp
src/CppUTest/CommandLineTestRunner.cpp
tests/CppUTest/CommandLineArgumentsTest.cpp
tests/CppUTest/CommandLineTestRunnerTest.cpp

Added help text. Couldn't remember all options

---

include/CppUTest/TestRegistry.h
include/CppUTest/Utest.h
src/CppUTest/CommandLineTestRunner.cpp
src/CppUTest/TestRegistry.cpp
src/CppUTest/Utest.cpp
tests/CppUTest/ShuffleTest.cpp
tests/CppUTest/TestRegistryTest.cpp

Cleaned up shuffling and added reversing. Not able to use yet.

Cleaned up shuffling some more and added reversing

---

include/CppUTest/CommandLineArguments.h
src/CppUTest/CommandLineArguments.cpp
src/CppUTest/CommandLineTestRunner.cpp
tests/CppUTest/CommandLineArgumentsTest.cpp
tests/CppUTest/CommandLineTestRunnerTest.cpp

Running the tests in reverse from normal

---

src/Platforms/Gcc/UtestPlatform.cpp
tests/CppUTest/UtestPlatformTest.cpp

Added max retry count, which causes gdb not be end up in endless loop

GDB working again on MacOsX for now... 

---

include/CppUTest/StandardCLibrary.h
src/CppUTest/SimpleString.cpp

Moved the va_copy hack into the StandardCLibrary.h

---

platforms/iar/CppUTestTest.ewp
platforms/iar/CppUTestTest.icf

I have added some missing tests to the IAR platform which probably were added since I last looked at this.
I was too quick creating pull request #1097. This could be included there, but I don't know how to remove my own pull request :-)

IAR: Adding missing tests

---

configure.ac
docker/Dockerfile.ubuntu
m4/m4_ax_compiler_vendor.m4
m4/m4_ax_compiler_version.m4
scripts/create_docker_images_and_containers

Report the compiler version. For some reason, the CXX doesn't seem to work. Not sure why.

Compiler version in configure script

---

docker/Dockerfile.gcc10
scripts/create_docker_images_and_containers

Updated the docker script and Dockerfile. Seems to work better now

---

.gitattributes

Made the automake files line-ending automatic

---

include/CppUTest/MemoryLeakWarningPlugin.h
src/CppUTest/MemoryLeakWarningPlugin.cpp

Use a safer method to toggle new/delete overloads.

---

CMakeLists.txt
examples/AllTests/CMakeLists.txt
examples/ApplicationLib/CMakeLists.txt
examples/CMakeLists.txt

This add option: EXAMPLES to cmake to be able build examples by cmake.
In build dir:
```
cmake -DEXAMPLES=ON ..
make
```

Add examples to cmake

---

.travis.yml
include/CppUTest/TestTestingFixture.h
include/CppUTest/Utest.h
src/CppUTest/TestMemoryAllocator.cpp
src/CppUTest/TestRegistry.cpp
src/CppUTest/TestTestingFixture.cpp
src/CppUTest/Utest.cpp
tests/CppUTest/MemoryLeakDetectorTest.cpp
tests/CppUTest/MemoryLeakWarningTest.cpp
tests/CppUTest/PluginTest.cpp
tests/CppUTest/TestMemoryAllocatorTest.cpp
tests/CppUTest/TestUTestMacro.cpp
tests/CppUTest/UtestPlatformTest.cpp
tests/CppUTest/UtestTest.cpp
tests/CppUTestExt/IEEE754PluginTest.cpp
tests/CppUTestExt/MockPluginTest.cpp
tests/CppUTestExt/MockSupportTest.cpp
tests/CppUTestExt/OrderedTestTest.cpp

and resolved some leaks in FailableMemoryAllocator

Improvements in TestTestingFixture

---

src/Platforms/Gcc/UtestPlatform.cpp

Lets see if this fixes the compilation problems in mingw without secure functions

Lets see if this fixes the compilation problems in mingw

---

scripts/README.txt

Fixing typo s/chmod *.sh/chmod +x *.sh/

Update README.txt fixing chmod command syntax

---

README.md

There is no CMakeList.txt file so I guess it was a typo on line 37..

Fix reference to CMakeLists.txt (add missing s)

---

README.md

Just tried to open this link and found it broken so fixed it with a working one, hope that helps

fix project page link

---

src/CppUTest/TestRegistry.cpp

This might fix the broken build.

Fix a warning related to printing line numbers

---

src/CppUTest/TestFailure.cpp

Fixes compilation problems reported in https://github.com/cpputest/cpputest/pull/1550#issuecomment-1100298904

Fix compilation with some not fully C++11 compliant compilers

---

CMakeLists.txt
config.h.cmake
include/CppUTest/CppUTestConfig.h

Addresses #1571 (at least for CMake)

Detect fenv.h in CMake

---

CMakeLists.txt
config.h.cmake
include/CppUTest/CppUTestConfig.h

https://cmake.org/cmake/help/latest/module/CheckTypeSize.html

Detect `long long` support in CMake

---

.circleci/config.yaml

The Travis 'free' build time was quickly spend and has not build for 6 months. Such a crap. Never sell your company and fuck over open source developers

Hello World CircleCI file. Looking for replacing TravisCI.

---

include/CppUTest/CppUTestConfig.h
tests/CppUTest/AllocationInCppFile.h
tests/CppUTest/TestFailureTest.cpp
tests/CppUTest/UtestPlatformTest.cpp
tests/CppUTest/UtestTest.cpp

Fixes some warnings reported by newer versions of Clang.

Fix compilation on clang

---

tests/CppUTest/MemoryOperatorOverloadTest.cpp

GCC 12 reports an use-after-free warning for two test cases.

Fix GCC 12 compilation

---

config.h.cmake
include/CppUTest/CppUTestConfig.h
tests/CppUTest/CMakeLists.txt

This reverts commit af6e54ce85e1085fa947d1965f46915413ad9ad7.

Revert "Reduce scope of CPPUTEST_HAS_INF"

---

CMakeLists.txt

https://cmake.org/cmake/help/latest/command/project.html

Leverage native project versioning

---

.github/workflows/basic.yml

Restore -Werror to CI builds

---

src/CppUTestExt/CMakeLists.txt
tests/CppUTest/CMakeLists.txt
tests/CppUTestExt/CMakeLists.txt

https://cmake.org/cmake/help/latest/module/FindThreads.html

Update FindThreads usage

---

CMakeLists.txt

Avoid unnecessary FindPkgConfig

---

.github/workflows/extended.yml
include/CppUTest/CppUTestConfig.h
include/CppUTest/UtestMacros.h
include/CppUTestExt/MockCheckedActualCall.h
include/CppUTestExt/MockNamedValue.h
include/CppUTestExt/MockSupport_c.h
src/CppUTest/SimpleString.cpp
src/CppUTest/Utest.cpp
src/CppUTestExt/MockActualCall.cpp
src/CppUTestExt/MockExpectedCall.cpp
src/CppUTestExt/MockNamedValue.cpp
src/CppUTestExt/MockSupport.cpp
src/CppUTestExt/MockSupport_c.cpp
tests/CppUTest/SimpleStringTest.cpp
tests/CppUTest/TestFailureTest.cpp
tests/CppUTest/TestHarness_cTest.cpp
tests/CppUTest/TestUTestMacro.cpp
tests/CppUTestExt/MockActualCallTest.cpp
tests/CppUTestExt/MockExpectedCallTest.cpp
tests/CppUTestExt/MockParameterTest.cpp
tests/CppUTestExt/MockReturnValueTest.cpp
tests/CppUTestExt/MockSupport_cTest.cpp
tests/CppUTestExt/MockSupport_cTestCFile.c

~I broke this.~ I think this has been broken for a while. I've added it to CI to prevent future regressions.

Fix use with `long long` disabled

---

.github/workflows/basic.yml
.github/workflows/extended.yml
CMakePresets.json

- Merge all the CMake workflows into a single matrix
- Give each config a name
- Add C++20 builds
- Add a DOS/CMake build

Consolidate and expand CI workflows

---

.github/workflows/extended.yml
.github/workflows/test-report.yml
cmake/Modules/CppUTest.cmake

JUnit reporting

---

.github/workflows/basic.yml
.github/workflows/test-report.yml

Merge similar jobs and give everything a friendly name.

Workflow polish

---

.github/workflows/basic.yml

https://github.com/marketplace/actions/build-and-push-docker-images
If we run into rate limits, we may have to set up a Docker Hub account. I've set it up to conditionally do a login when the credentials are set.

Port Docker builds from Travis

---

.github/workflows/basic.yml
Makefile_using_MakefileWorker

* Call _all_ of the makefile setup
* Move logic out of workflow YAML back to the Makefile

Improve Makefile Worker CI

---

.github/workflows/basic.yml

Remove scheduled workflows

---

.github/workflows/basic.yml
include/CppUTest/CppUTestConfig.h
tests/CppUTest/MemoryOperatorOverloadTest.cpp

Ensure that exception specifications match for delete overloads

---

CMakePresets.json

New release yesterday broke: https://hub.docker.com/r/multiarch/qemu-user-static

Pin working qemu image

---

README.md

Updated README.md to address missing information that could potentially lead to misunderstandings, particularly for new users. This enhancement ensures that the documentation is more comprehensive and user-friendly.

Improve README.md Clarity

---

examples/AllTests/EventDispatcherTest.cpp

Ensuring the list include works when overloading the realloc

Fix realloc build failure with clang

---

tests/CppUTest/JUnitOutputTest.cpp

Fixing PlatformSpecificFPuts conflict between JUnitOutputTest and TestOutput

---

src/CppUTest/CommandLineTestRunner.cpp

Removed #include too much

---

include/CppUTest/CppUTestConfig.h

Suppress warning from generated autotools header

---

tests/CppUTest/UtestTest.cpp

Added stub for srand so that it doesn't depend on the implementation of srand
