cpputest/cpputest

.gitignore
When building the VS201x projects, I noticed that git status shows the release folders as being changes, so I added them to the ignore list.
@arstrube I don't see your linker warnings, I built both Debug and Release configurations of CppUTest and the Examples.  One thing I did just remember, there was a known issue with VS2010 and VS2012 coexisting that was fixed in VS2010SP1, so if you didn't have the service pack installed before installing VS2012, that may be why you had problems.  One possible way to clean things up may be to install Service Pack 1 if you don't already have it installed.
=> Added the release folders to the ignore list

tests/SimpleStringTest.cpp
Up to now, the 64 bit pointer printing test would have been silently omitted on 32-bit systems.
I suggest replacing this with an empty IGNORE_TEST() on incompatible systems.
Note: This drops my hack for 64 bit Windows. I consider it a hack, rather than a test of anything useful. So I am rather glad to see it gone.
The number of testcases should now be identical (with regard to this particular conditional compilation), regardless of target system.
=> Use IGNORE_TEST() on incompatible systems.

tests/SimpleStringTest.cpp
Rewrote test so it will compile on all 32 bit and 64 bit systems.
We now have the following distinct scenarios:
1. Test will pass on 64 bit systems with 64 bit longs
-> TEST().
2. Test should pass on 64 bit systems with 32 bit longs, but fails
due to a known implementation problem. Needs to be fixed.
-> IGNORE_TEST() for now.
3. Test cannot pass on 32 bit systems
-> IGNORE_TEST() always.
=> Handling the 64 bit test case in a cleaner way

include/CppUTest/TestResult.h, include/CppUTest/Utest.h, src/CppUTest/JUnitTestOutput.cpp, src/CppUTest/TestOutput.cpp, src/CppUTest/TestRegistry.cpp, src/CppUTest/TestResult.cpp, src/CppUTest/Utest.cpp, tests/JUnitOutputTest.cpp, tests/TestOutputTest.cpp
Fixes #462.  It's not a very good solution, just checks what character the progress indicator is, but it works.  It looks to me like there is some unneeded coupling going on between the TestOutput logic and the UTestShell class since it knows the character that gets printed.  I think that it should probably just know it's status and let the TestOutput class decide which character that means gets printed, or in the case of JUnit Output, what to put into the file.
=> Added support for outputting skipped tests to junit

Makefile.am
Looks like this is the best place to disable optimizations for the coverage build.
=> Explicitly disable optimizations for coverage build

include/CppUTest/PlatformSpecificFunctions.h, src/Platforms/Gcc/UtestPlatform.cpp, src/Platforms/GccNoStdC/UtestPlatform.cpp, tests/UtestTest.cpp
Add TEST(UtestShell, RunInSeparateProcessTest).
This will test the part relevant to UtestShell without creating an actual separate process.
=> 2. utestshell

src/Platforms/VisualCpp/UtestPlatform.cpp
PlatformSpecificRunTestInASeperateProcess was modified to be a function pointer as part of pull request #494.  That change wasn't also applied to the VisualCpp copy of UtestPlatform.cpp, so I applied it to this file as well.
=> Applied change from #494 to Visual C++

include/CppUTest/TestOutput.h, include/CppUTestExt/MockCheckedActualCall.h, src/CppUTest/TestOutput.cpp, src/CppUTestExt/MockActualCall.cpp
These are never used anywhere (and also, not tested, of course).
Since it is not likely they would be used by anyone outside of CppUTest, I removed them (rather than adding tests for them).
=> Removed some redundant methods

CppUTest.dsp, makeAndRun.bat, tests/AllTests.dsp
This pull request is the first replacement for #513. It fixes up the .dsp files and puts back makeAndRun.bat. for VC6
- All CppUTestExt sources and tests included
- Memory leak detection disabled (until such time that someone fixes up new[])
- Compiles and links successfully
- Note that this will still crash in running the tests, because some tests need fixing
=> Vc6 1 - Fixup broken VC6 project

CppUTest.sln, CppUTest.vcproj, tests/AllTests.vcproj
Project files and solution for VS2005.
I imported the new VC98 workspace into VS2005.
I also imported this solution into VS2008, which compiled and ran successfully.The same is true of VS2010. 
In the interest of less maintenance, I was wondering whether we should maybe drop the xx_VS2008 (and possibly _VS201x) files and provide xx_VS2005 only instead. 
What does everybody think about that? The only snag is that we would need a relatively ancient copy of VS around for maintenance. I am willing to do that (and relatively unwilling to set up a VM running VS2008/10 on my Mac). 
Looking at the diff for the converted vcxproj's, it seems that it contains quite a bit of redundant stuff, but it works.
=> Regenerated and test solution (VS2005)

include/CppUTest/TestOutput.h, src/CppUTest/TestOutput.cpp
by making pointless TestOutput::flush () pure virtual.
=> 100% statement coverage for TestOutput.cpp

Makefile.am
$ in front of variables caused them to turn into FLAGS and XXFLAGS. Fix this.
Also, add the same variables for Clang.
=> Fix to Makefile.am

tests/CommandLineTestRunnerTest.cpp
Last pull request caused errors in my VC build.  Looks like it doesn't like treating the constructor as a static function as part of an initializer list.  I'm a bit surprised that other compilers didn't mind this, I don't think I've ever seen it before.
=> Fixed base class constructor call

CppUTest.vcxproj
This will prevent the warning about using unsafe functions.
=> VS201x should define the STDC_WANT_SECURE_LIB macro

tests/CppUTestExt/MockSupportTest.cpp
using test in separate process on platforms that support fork().
Also add test for an unnamed MockNamedValue and for MockFunctionComparator::valueToString().
=> Add test for MockSupport::crashOnFailure()

build/MakefileWorker.mk
I had a same problem (#488).
If SRC_DIRS is `src` and has only C or CPP files, gcov_error.txt has
> objs/src/*.gcno:cannot open notes file
=> gcov not run in the right when SRC_DIRS has only C or CPP files

src/CppUTestExt/MockExpectedCall.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockExpectedFunctionsListTest.cpp
This one follows (and includes) #558
=> mecl - 100% Coverage for MockExpectedCallList

tests/CppUTestExt/MockSupportTest.cpp
Error introduced by PR 575 (I think), the test group inside the preprocessor #if block was changed, but the test group inside the #else block was not changed.
=> Change the test group to match the new name

include/CppUTestExt/MockFailure.h, include/CppUTestExt/MockSupport.h, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockSupportTest.cpp
So we can de-activate crashOnFailure after testing it
=> Add a boolean argument to crashOnFailure()

tests/CppUTestExt/MockSupport_cTest.cpp, tests/CppUTestExt/MockSupport_cTestCFile.c
because crashOnFailure_ is never passed to
MockFailureReporterTestTerminatorForInCOnlyCode.
=> 100% Coverage for MockSupport_c - Part 1

src/CppUTestExt/MockSupport_c.cpp
Exclude unhittable lines from lcov. 
I can't say I am entirely happy with excluding the destructor (although it does nothing), but for the life of me I can't figure out why it never gets called, and the destructors of all the other terminators do. :-(
Also, I'm not entirely sure that hasFailed() couldn't be true (but then if it was, the test should have been terminated already?), and if it couldn't be true, I'd prefer to get rid of the condition altogether (which would justify the } being __really__ unhittable)...
=> 100% Coverage For MockSupport_c - Part 2

CMakeLists.txt, include/CppUTest/CommandLineArguments.h, include/CppUTest/TestRegistry.h, src/CppUTest/CommandLineArguments.cpp, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/TestRegistry.cpp, tests/CMakeLists.txt, tests/CommandLineArgumentsTest.cpp, tests/CppUTestExt/CMakeLists.txt, tests/TestRegistryTest.cpp
* added commandline switch -lg for printing all test group names instead of running them
* added switch -ln printing list of all group.test pairs
* switch -ln use groups filter
* tests added for new command line arguments
=> Print test group names

src/CppUTestExt/MockFailure.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockSupportTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp, tests/MemoryLeakOperatorOverloadsTest.cpp, tests/TestHarness_cTest.cpp, tests/TestMemoryAllocatorTest.cpp, tests/TestUTestMacro.cpp
Separate pull request for Lcov exclusions. Mostly unhittable lines either in IGNORE_TEST or  at the end of fail methods.
=> lcov - Exclude unhittable lines for lcov

tests/UtestTest.cpp
I think we agreed on using IGNORE_TEST() when excluding tests from certain platforms, to minimize variances in test count between platforms. I forgot this one.
=> ignt - Add missing IGNORE_TEST for VS / MinGW

include/CppUTest/SimpleString.h
It turns out I overlooked a redundant #include <stdint.h> in SimpleString.h. This needs to go for VisualCpp to work properly without <stdint.h>.
=> stdint2 - Fix

examples/AllTests/AllTests.vcxproj, examples/ApplicationLib/ApplicationLib.vcxproj
...in the example projects.
The dependency on platform-specific headers is unnecessary and confusing.
It also led to some problems with an obsolete (now already deleted) version of stdint.h being attracted into user projects.
The solution to VC6 ff will take a little longer, as the example project files are not working.
=> VS201x - Removed confusing include-path

src/Platforms/Gcc/UtestPlatform.cpp, tests/UtestPlatformTest.cpp
caused by waitpid() failing with errno == EINTR.
Fixes issue #615.
=> Fix Mac OS X debugger failures

include/CppUTest/Utest.h, src/CppUTest/Utest.cpp, tests/UtestPlatformTest.cpp
Moved the division in a separate compilation unit so that the compiler can't optimize it away anymore. HAH :)
=> Fixed the problem of optimizing away division by zero

include/CppUTest/SimpleString.h, include/CppUTest/TestFailure.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, src/CppUTest/SimpleString.cpp, src/CppUTest/TestFailure.cpp, src/CppUTest/Utest.cpp, tests/SimpleStringTest.cpp, tests/TestFailureTest.cpp, tests/TestUTestMacro.cpp
I've implemented the MEMCMP_EQUAL feature in my fork. Feel free to use any part of my code if you find it useful. It's output look like this:
```
../mainTest.cpp:16: error: Failure in TEST(MemCmpDemo, Demo)
expected <01 23 45 67>
but was  <01 23 00 67>
difference starts at position 2 at: <   01 23 00 67      >
^
```
=> MEMCMP_EQUAL assertion

tests/CommandLineTestRunnerTest.cpp
Due to CommandLineTestRunnerWithStringBufferOutput overriding some methods for testing, the original methods weren't tested anymore.
This test tests the original methods.
=> Test JUnitOutput properly again

tests/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
It seems that when compiling using MinGW, the pthread library has to be linked explicitly, so I've modified the CMakeLists to do so when using that compiler.
NOTE: cmake's find_package(Threads) is buggy, at least at version 2.8.12, as ${CMAKE_THREAD_LIBS_INIT} is not set properly (it's actually empty), therefore this variable is not used to add the library to the linker.
=> Added proper pthread library linking when using CMake and MinGW to compile

src/CppUTest/TestRegistry.cpp, tests/TestRegistryTest.cpp
* TestRegistry::listTestGroupNames() put each of grup in #name# before
putting into temporary list. This will prevent missing of GROUP1
in the list when GROUP11 was already there
* TestRegistry::listTestGroupAndCaseNames() - just like above
=> Fix test groups listing feature

include/CppUTest/Utest.h, src/CppUTest/Utest.cpp, tests/UtestPlatformTest.cpp, tests/UtestTest.cpp
of too many problems with different compilers / architectures.
=> Remove division-by-zero tests again because

include/CppUTest/CppUTestConfig.h
Fixes a problem that caused compiler warnings when compiling using MinGW, if standard C library headers (e.g. stdint.h) are included before cpputest headers (e.g. MockSupport.h).
The problem was that standard headers include "%MINGW_DIR%/include/_mingw.h", which defines the macro __USE_MINGW_ANSI_STDIO, but CppUTestConfig.h also defines that macro unconditionally, and therefore the compiler complains about macro redefinition.
=> Fixes a problem with warning when compiling with MinGW

CMakeLists.txt, CppUTestConfig.cmake.build.in, CppUTestConfig.cmake.install.in, src/CppUTest/CMakeLists.txt, src/CppUTestExt/CMakeLists.txt
Generate appropriate CppUTestConfig.cmake files so `find_package` works properly.
After installing CppUTest (using cmake) under one of the predefined default locations other projects may find it by calling `find_package(CppUTest)`. After successful call variable `CppUTest_INCLUDE_DIRS` should be initialized with path to CppUTest headers and `CppUTest_LIBRARIES` variable should be initialized with appropriate targets to link with, e.g.
```
find_package(CppUTest  REQUIRED NO_CMAKE_PATH)
include_directories(${CppUTest_INCLUDE_DIRS})
target_link_libraries(my_tests ${CppUTest_LIBRARIES})
```
If you wish to use CppUTest installed under non-standard location use `CppUTest_DIR` variable to point out directory with appropriate CppUTestConfig.cmake file. It is usually installed under …
=> Cmake improve

CMakeLists.txt, cmake/Modules/CppUTestBuildTimeDiscoverTests.cmake, cmake/Scripts/CppUTestBuildTimeDiscoverTests.cmake, tests/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
Improve the CMake infrastructure by doing (post)-build-time test discovery. 
Currently `tests/CMakeLists.txt` executes  the `tests/CppUTestTests` binary at configure-time to obtain a list of tests to be added using the ADD_TEST() command. This is a problem because:
* The `tests/CppUTestTests` binary does not exist when staring with a clean build-tree
* New tests are not detected until a reconfigure is issued.
The proposed patch generates ADD_TEST() commands from a test list obtained by invoking the binary containing the tests *after* the binary has been build.
Now test discovery is done my invoking `cpputest_buildtime_discover_tests ()` e.g. in `tests/CMakeLists.txt`:
cpputest_buildtime_discover_tests (CppUTestTests)
=> CMake build-time test discovery

include/CppUTest/SimpleString.h, include/CppUTest/TestFailure.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, src/CppUTest/SimpleString.cpp, src/CppUTest/TestFailure.cpp, src/CppUTest/Utest.cpp, tests/SimpleStringTest.cpp, tests/TestFailureTest.cpp, tests/TestUTestMacro.cpp
I've created an assertion for checking the equality of the specified bits in a value. Here's an example of it's usage:
```
TEST(BitsDemo, Demo) {
uint16_t expected = 0x1234;
uint16_t actual = 0xFF74;
uint16_t mask = 0x00F8;
BITS_EQUAL(expected, actual, mask)
}
```
The output:
```
TestBits.cpp:10: error: Failure in TEST(BitsDemo, Demo)
expected <xxxxxxxx 00110xxx>
but was  <xxxxxxxx 01110xxx>
```
I used the sizeof operator on the actual value for determine the number of bits that the error message should display. I don't know if it's good or it's not. I think it's not so nice when I'm checking a variable with the length of 8 bits then I get an error message containing 64 bits. There can be another solution for this problem, if there are separate test macros for the integers with different …
=> BITS_EQUAL assertion

src/CppUTest/CMakeLists.txt, src/CppUTestExt/CMakeLists.txt
Added headers to cmake's library files to obtain proper projects with proper headers when creating an eclipse project.
Without this patch, when creating an eclipse project using cmake (e.g. cmake -G "Eclipse CDT4 - MinGW Makefiles"), the header files don't appear in the target's headers, which makes indexing not working properly, and finding them a bit harder.
=> Fixed eclipse project generation using cmake

CppUTestConfig.cmake.build.in
Without this change recent cmake versions (>3.0) reports warning during configure phase.
=> do not include config if target is already defined

include/CppUTest/CppUTestConfig.h, include/CppUTest/MemoryLeakDetectorNewMacros.h, include/CppUTest/Utest.h, include/CppUTestExt/MockCheckedExpectedCall.h
While compiling with Clang 3.6 I got some warnings.
These changes will suppress these warnings.
=> Clang 3.6 warnings

include/CppUTest/SimpleString.h, src/CppUTest/SimpleString.cpp, tests/SimpleStringTest.cpp
* Fixed the memory leak reported in #665 
* Added additional debug info in SimpleString
* Ensured SimpleString tests use the memory leak detector
* Fixed an additional memory leak when replacing results in an empty string
=> Fixed TWO memory leaks in SimpleString. Shame on us :)

src/CppUTestExt/MockActualCall.cpp, tests/CppUTestExt/MockSupportTest.cpp
=> Fix bug when ignoreOtherParameters() is combined with withOutputParameter()

include/CppUTestExt/MockNamedValue.h, include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupportPlugin.h, src/CppUTestExt/MockNamedValue.cpp, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupportPlugin.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockSupportTest.cpp
As the title says. Now we can add NamedValueCopier to the Node and voila!
=> Changing the name of the Comparators repository so we can add copiers to it :)

include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockExpectedCallsList.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCallsList.cpp, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockExpectedFunctionsListTest.cpp
Added this so if it's merged then PR #707 changes will be more readable.
=> Fixed spelling errors in function names and constants.

src/CppUTest/SimpleString.cpp, src/CppUTest/TestFailure.cpp, tests/SimpleStringTest.cpp
Since NaN and Infinity are full citizens of the floating point universe, I propose to move printing "Nan - Not a number" and "Inf - Infinity" directly into SimpleString.
Actually, under Gcc, StringFromFormat would print "Nan" and "Inf" in any case, so why not allow this little bit of extra verbosity outside of failures as well (actually I found it confusing that sometimes "Nan" would be printed and other times "Nan - Not a number".
This can also be tested very easily in SimpleString by having the platform-specific functions just return `true` always for those tests.
=> Move printing of Nan and Inf to StringFrom(double)

tests/UtestTest.cpp
When I build in MacOS using following commands:
```
$cmake
$make
```
I get following error message:
> error: comparison of address of 'this->fixture' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
The fixes the above error.
=> fix a compile error

include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockExpectedCallsList.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCallsList.cpp, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockActualCallTest.cpp, tests/CppUTestExt/MockExpectedFunctionsListTest.cpp, tests/CppUTestExt/MockSupportTest.cpp
This PR fixes the problem detailed in #706.
The changes basically consist in not resetting the "actual call fulfillment state" of other potentially matching calls with more requisites (i.e. parameters) when the first fulfillment is done. 
Instead, each time a parameter is passed, if an expected call was previously fulfilled then it's "unfulfilled" (because it isn't actually matching the actual call), and other expected calls that could be previously fulfilled are also discarded. That way, as parameters are passed, expected calls with too few parameters are discarded, and the set of "fulfillable" expected calls is narrowed down.
Finally, when checkExpectations() is called on the last actual call, the "actual call fulfillment state" of the remaining unfulfilled expected calls is reset. This …
=> Fixed errors when mocking overloaded functions

include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockSupport_cTest.cpp, tests/CppUTestExt/MockSupport_cTestCFile.c
@basvodde -- while this does work as is, I am not really sure whether I added enough, or too much. 
Should this be part of `sMockValue_c`?  If so, one could use it as a return value. Should one be able to do that?
Are the tests sufficient? Or too many? I haven't used these interfaces recently, so I am not too sure.
=> Added missing mock_c() withMemoryBufferParameter() interfaces

src/CppUTest/TestFailure.cpp, tests/CppUTestExt/MockSupportTest.cpp, tests/SimpleStringTest.cpp
The 4 byte bit-masked tests contained two errors in the 16 bit branch.
On 16 bit platforms, when floats are promoted to double, the result is in inexact. Due to this, the double test failure test will fail, if we set precision to higher than 7 here.
=> Fixes for Cl2000

tests/UtestPlatformTest.cpp, tests/UtestTest.cpp
This should work for arm/linux/gcc as well as for arm/keil
It specifically checks for the armcc compiler, rather than for the arm architecture.
=> Quick fix for the fork-problem

tests/CppUTestExt/MockSupport_cTestCFile.h
Identifier starting with double underscore  are reserved ([info](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)).
=> Reserved identifier replaced

include/CppUTest/TestFailure.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, src/CppUTest/TestFailure.cpp, src/CppUTest/TestHarness_c.cpp, src/CppUTest/Utest.cpp, tests/CppUTestExt/CodeMemoryReportFormatterTest.cpp, tests/CppUTestExt/MemoryReportFormatterTest.cpp, tests/TestFailureNaNTest.cpp, tests/TestFailureTest.cpp, tests/TestHarness_cTest.cpp, tests/TestUTestMacro.cpp
Added the missing complementary macros for all the current assert macros. 
The new ones accept a user message that is printed if the assertion fails (like CHECK_TEXT or CHECK_TRUE_TEXT), and follow the same nomenclature (CHECK_xxx_TEXT).
=> Check macros with custom messages

src/CppUTest/MemoryLeakDetector.cpp
The length specifier `hh` was [introduced with C99](http://www.cplusplus.com/reference/cstdio/fprintf/) and is not supported by C++98.
Therefore compiling CppUTest with C++11 *disabled* fails.
--------
Tested with GCC 5.2 and `cmake -DC++11=OFF`.
=> Length specifier fixed for C++98

.travis.yml, README.md, scripts/travis_ci_build.sh
I was messing around with [Coveralls](http://coveralls.io) (which if you don't know is an online service that allows tracking code coverage, it's free for open source projects, and really easy to use because you can sign-in with the github account), and I added support to automatically update CppUTest coverage from Travis-CI builds.
It doesn't support branch coverage, but anyway it may be useful to check in a glance PR's proper testing, so I'm PRing this just in case you find it useful.
In case this is merged, remember to enable coverage for the cpputest repo in [Coveralls](http://coveralls.io),
=> Coveralls online code coverage

tests/CppUTestExt/MockFailureTest.cpp, tests/CppUTestExt/MockFailureTest.h
from MockSupportTest.cpp to MockFailureTest.cpp
(MockFailureReporterForTest is used in MockSupportTest, too, but getReporter() was defined in MockFailureTest.cpp).
=> Remove ugly dependency

CMakeLists.txt
Now also for Cmake, when fork() is available, HAVE_FORK is defined and CppUTest is built so that running tests in a separate process will work. 
(The previous pull request did not really work for Cmake; the build would always be without support for running in a separate process, and HAVE_FORK would never be defined).
=> Cmake and HAVE_FORK working properly at last

.gitignore, .travis.yml, platforms/Dos/Makefile, platforms/Dos/dosbox-0.74.conf, scripts/travis_ci_build.sh
At this point, it's just a dummy stiil.
What it does do
+ Install Dosbox
+ Invoke the appropriate build
+ Run the proper Makefile
+ Run Dosbox & produce dummy test output from within to a log
+ Print the log
What's still missing
+ Watcom compiler install
+ Proper implementation of Makefile
+ Script to run the actual 6 targets in Dosbox
+ Fail the test if "Failure" is found in the log.
=> Put 16-bit Build Dummy Into Travis

platforms/Dos/Makefile, tests/CppUTestExt/MockComparatorCopierTest.cpp, tests/SimpleStringTest.cpp
Heed some, squash most, and enable warnings=error
Fixes issue #765.
=> Dos build: Fix Warnings as Errors

include/CppUTest/SimpleString.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, include/CppUTestExt/MockActualCall.h, include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCall.h, include/CppUTestExt/MockNamedValue.h, include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupport_c.h, src/CppUTest/SimpleString.cpp, src/CppUTest/Utest.cpp, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockNamedValue.cpp, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockActualCallTest.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockParameterTest.cpp, tests/CppUTestExt/MockReturnValueTest.cpp, tests/CppUTestExt/MockSupportTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp, tests/CppUTestExt/MockSupport_cTestCFile.c, tests/SimpleStringTest.cpp, tests/TestUTestMacro.cpp
Mixing function and data pointers isn't allowed when compiling in pedantic mode. Attempting to use the CppUTest pointer assertions or mock support causes the following compiler errors:
clang: "error: cast between pointer-to-function and pointer-to-object is an extension [-Werror,-Wpedantic]"
gcc: "error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]"
This patch adds explicit function pointer support. Sorry it's huge. It touches quite a few files.
=> Add function pointer support.

include/CppUTest/TestMemoryAllocator.h, include/CppUTestExt/MockFailure.h, include/CppUTestExt/MockNamedValue.h
Found some more unneeded empty overridden destructors while checking Coveralls report.
=> Get rid of some more overridden empty destructors

include/CppUTest/TestHarness_c.h, include/CppUTest/Utest.h, src/CppUTest/TestHarness_c.cpp, src/CppUTest/Utest.cpp, tests/TestHarness_cTest.cpp
This allows users of the C interface to compare pointers and get proper feedback based on the failure state.
=> Add CHECK_EQUAL_C_POINTER

build/MakefileWorker.mk, cmake/Modules/CppUTestConfigurationOptions.cmake, cmake/Modules/CppUTestWarningFlags.cmake, configure.ac
Add -Wno-reserved-id-macro and -Wno-keyword-macro to clang builds. Fixes CppUTest on Xcode 7+, with clang-700+, where warnings were added about using reserved namespaces like __, and for macros that shadow keywords.
=> Fix CppUTest for OSX / Xcode7 / clang-700.x

Makefile.am, configure.ac
enable [subdir-objects] in AM_INIT_AUTOMAKE, fix bug in Makefile.am. Subdirectory artifacts like Platforms/Gcc/... now get correct output directories.
=> Quieter autoconf

CMakeLists.txt
``libdir`` and ``includedir`` variables in cpputest.pc don't take ``exec_prefix`` and ``prefix`` into account.
=> CMake generates malformed cpputest.pc 

include/CppUTest/CommandLineArguments.h, include/CppUTest/TestFilter.h, src/CppUTest/CommandLineArguments.cpp, src/CppUTest/TestFilter.cpp, tests/CommandLineArgumentsTest.cpp, tests/TestFilterTest.cpp
Implementation for issue #107.
New command line options:
`-xg <group>`: exclude test groups matching `group` string. 
`-xn <name>`: exclude test names matching `name` string.
`-xsg <group>`: exclude test group strictly matching `group` string.
`-xsn <name>`: exclude test names strictly matching `name` string.
Working use cases are:
* Exclude one test group.
* Exclude one test name.
* Exclude one test name within a group.
* Filter one test name in all but one excluded group.
* Exclude one test name in all but one excluded group.
Since test filter combination is implemented as a set union rather than intersection, combining two or more non-overlapping exclude group options, i.e. `-xg group1 -xg group2` turns out to run the full list of tests including all groups. Same thing happens when …
=> Additional filters to exclude tests based on group and/or name

appveyor.yml, scripts/appveyor_ci_build.ps1, scripts/appveyor_ci_test.ps1
I finally got autotools working via cygwin on AppVeyor.  I think there was an open issue for this a while ago that got closed.
Anyways, it runs and shows the test results the same as MinGW or Visual C++.  For some reason, Cygwin results in the most tests being run compared to the other two environments.  I'm not sure everything I added is needed, but I'll look at doing some cleanup later this week and might remove a few things then (mostly around the install logic).
=> Appveyor support for Cygwin/autotools

tests/AllTests.vcproj, tests/AllTests.vcxproj
This is some cleanup to the visual studio project files to add some missing test files.  I noticed this on appveyor when adding autotools, VS was running a couple hundred fewer tests than autotools or MinGW.
I haven't been able to update/test the VC6 project, I can run builds but don't have the IDE available to regenerate certain files.  Looks like it broke as part of PR #603, so I think it's been broken for a while.  `CppUTest.dep` is looking for `include\Platforms\VisualCpp\stdint.h` which no longer exists and it doesn't know how to create it.
=> Added missing test files to visual studio projects

include/CppUTest/TestTestingFixture.h, tests/UtestTest.cpp
The separate process test returned a different signal. Looking into it, it seems that signal is also valid and thus it shouldn't fail the test. For now, created a test that has an 'or' in it which checks both signals. Not the best choice, but I guess it will do for now?
@arstrube: Might want to check this one. You think this fix is ok?
=> Fixed a failed test on clang++3.7.

tests/AllTests.dsp, tests/CppUTestExt/MockFailureTest.h
(actually, it is the method `MockFailureReporterForTest::getReporter()` that must not be inlined)
=> Put the Vc6 fix where it belongs

include/CppUTestExt/MockSupport.h, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockCallTest.cpp
after several implementations try, I chose this as my solution to for the expecting no call functionality. It's the more balanced one, for satisfying the simplicity , sufficient and compliant with existed system design requirement .
Let's see if it's worth to be added.
#Solution Description
add one unexpected list in MockSupport, and add one expectNoCall in MockSupport. When expectNoCall() is invoked, One unexpected call will be appended to the unexpected list.
then in actualCall(), current existed expectation empty judge will changed to judge if both expectation list and unexpectation list are empty. If expectation list is empty and unexpectation list is not empty, actualCall() will go ahead to trigger the unexpected call failure.
=> Fix for #817 one balanced implementation for expecting no call functionality

scripts/travis_ci_build.sh
=> Add -l to gcov options, so inline functions will be analyzed correctly.

include/CppUTestExt/MockExpectedCallsList.h, include/CppUTestExt/MockSupport.h, src/CppUTestExt/MockExpectedCallsList.cpp, src/CppUTestExt/MockFailure.cpp, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockStrictOrderTest.cpp
For current fix for #829 , I'm afraid if lastActualFunctionCall is null then we lost chance to check other scope out of order.
for example:
```.cpp
mock().strictOrder();
mock("bla").strictOrder();
mock().ignoreOtherCalls();
MockExpectedCallsListForTest expectations;
expectations.addFunction("foo1", 1)->callWasMade(2);
expectations.addFunction("foo2", 2)->callWasMade(1);
MockCallOrderFailure expectedFailure(mockFailureTest(), expectations);
mock("bla").expectOneCall("foo1");
mock("foo").expectOneCall("foo1");
mock("foo").expectOneCall("foo2"); 
mock("bla").actualCall("foo1");
mock("foo").actualCall("foo2");
mock("foo").actualCall("unexpected1");
mock("foo").actualCall("foo1");
mock("foo").actualCall("unexpected2");
```
I admit i'm fastidious about the out of order check :)
I have another …
=> another proposed fix of #829

build/MakefileWorker.mk
This allows passing of additional arguments to gcov when using gcov for coverage analysis.
We include the MakefileWorker.mk in our unit test Makefile, and need to pass additional options to gcov. Our use case for this is to turn on branch coverage in gcov by passing the "-b -c" command line options.
=> Added GCOV_ARGS to MakefileWorker.mk

.travis.yml, scripts/travis_ci_build.sh
This fixes issue #809 - well a related issue which causes all jobs to error when for some reason Dosbox (which is only needed for `make_dos`) cannot be installed.
I tested the github deployer part on my fork and it work (installing correctly, then displaying a message that nothing will be deployed, because it is running on a for - all as expected). After that, I commented out the github deployer part again.
=> Prune install section in .travis.yml; install Dosbox only for make_dos.

CppUTest.vcxproj
``GTest.h  MockActualCall.h  MockExpectedCall.h`` is missing in vs2010's project `CppUTest.vcxproj`, they three should be added back for reading or modifying.
=> Add missing header file for CppUTest in vs2010 proj

CppUTest.vcxproj, include/CppUTest/SimpleString.h, src/CppUTest/SimpleString.cpp, src/CppUTestExt/MockFailure.cpp, tests/CppUTestExt/MockFailureTest.cpp, tests/SimpleStringTest.cpp
Previously, all such failures displayed a failure message containing "Unexpected additional (Nth) call", even for values such as 2, 3, etc.
This patch correctly differentiates based on English ordinal numbering rules, adding tests for all the special cases I could think of.  If I should break it into multiple tests, let me know!
(sorry, this must be the most nit-picky pull request of all time...)
=> Correct use of ordinal numbers in MockUnexpectedCallHappenedFailure

include/CppUTestExt/IEEE754ExceptionsPlugin.h, src/CppUTestExt/IEEE754ExceptionsPlugin.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp
1. Default argument for name (important for non-C++11 compilers)
2. Make declaration / implementation like in existing plugins
3. Minimum requirement for this to work is actually C99, not C++11.
Hence, use \<fenv.h\> rather than \<cfenv\>.
=> Three improvements to IEEE754Plugin

include/CppUTest/UtestMacros.h
The test macro `CHECK_THROWS()` uses the variable name `msg` internally. Since this name is also often used within tests, this will cause a build failure. It'll be better so change it so something less usual.
```cpp
... 
TEST(ExampleTest, nameConflict)
{
ExampleMessage msg;
CHECK_THROWS(std::exception, msg.willThrow());
}
```
This will result in an error `»class SimpleString« has no member named »willThrow«`.
=> Message variable name changed to avoid possible naming conflicts

examples/AllTests/AllTests.cpp, examples/AllTests/FEDemoTest.cpp, include/CppUTest/CppUTestConfig.h, include/CppUTestExt/IEEE754ExceptionsPlugin.h, src/CppUTestExt/IEEE754ExceptionsPlugin.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp, tests/CppUTestExt/IEEE754PluginTest_c.c
This one still faces at least two challenges:
1. Building without Standard C libraries fails (naturally) -- @basvodde what would be the cleanest way to deal with that? PlatformSpecifics function, perhaps?
2. Open Watcom does support `fenv.h`. However, I couldn't convince it to link the fe... functions... yet.
=> Get rid of C++11 requirement for IEEE754Plugin

include/CppUTest/UtestMacros.h, tests/TestUTestMacro.cpp
This change ensures expected/actual are put in parenthesis before calling (UNSIGNED_)LONGS_EQUAL_LOCATION().  This makes these macros expression-safe, equivalent to their counterparts (CHECK et al, POINTERS_EQUAL, etc.)
This prevents unwanted truncation and silences PC-Lint if the user writes a check like:
LONGS_EQUAL(c, a + b);
FWIW if the user uses the GCC flag -Wconversion=error, the above would cause a compilation error if a would lose precision when cast to (long) per the expansion:
assertLongsEqual(c, (long)a + b, ...)
=> Make LONGS_EQUAL(_TEXT)() and UNSIGNED_LONGS_EQUAL(_TEXT)() expression safe

appveyor.yml
I've rebased my previous pull request so that it shouldn't fail now.  This version runs both MinGW 4.8.5 and MinGW 5.3.0 on appveyor.  Hopefully this will help us see future failures like `isnan()` one that showed up recently.  Unfortunately, each MinGW configuration seems to take 10-15 minutes to run, so it does add 20-30 minutes to the build time.  Overall it looks like it's 45-70 minutes for appveyor to run, just based on the last couple builds I've seen on this branch.
Also, I've fixed the output from the unzip during the MinGW install command, it gets dumped to null for now.  I'm not the happiest about it since it also dumps the normal install command output, but until chocolatey gets updated to handle this itself, that's how it's going to be.
=> Run both MinGW 4.8.5 and MinGW 5.3.0 on appveyor

platforms/Dos/Makefile
@mmidor you will see some test failures in the Dos build after this is merged. Fixing those, I think, is your department :-).
@basvodde this only affects the Dos build.
=> Disable 'W472: expression with side effect in sizeof discarded' for wcl

CMakeLists.txt, cmake/Modules/CppUTestSetTestOutputLocation.cmake, tests/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
By default, Xcode (and VS?) build artifacts to a path that includes the configuration name. In Xcode's case, this was "Debug". CMake was expecting its self-test executables CppUTestTests and CppUTestExtTests to be in specific paths that did not include the configuration paths.
This PR forces Xcode to put the test executables in the same location that the other CMake generators (make / ninja) put them. This is also where the non-cmake autoconf builds put them.
Fixes https://github.com/cpputest/cpputest/issues/877
cc @basvodde
=> Fix cmake xcode

tests/CMakeLists.txt, tests/CppUTestExt/MockSupport_cTestCFile.c
Compilation is fixed with the following patches for the system:
$ uname -a
OpenBSD obi_64.abc.lan 5.8 GENERIC.MP#1236 amd64
$ cc -v
Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd5.8/4.2.1/specs
Target: amd64-unknown-openbsd5.8
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719
=> Compilation fixes for OpenBSD-5.8

tests/SimpleStringTest.cpp
Forgot to fix these tests -- some of them were still failing on the cl2000.
=> Fix SimpleString Tests for 16bit per byte systems (cl2000)

include/CppUTestExt/IEEE754ExceptionsPlugin.h, src/CppUTestExt/IEEE754ExceptionsPlugin.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp
When a test fails due to an an IEEE754 exception flag being set,
it can be hard to find exactly where the error occurred.
By entering the new static method in the debugger as a watch,
e.g. IEEE754ExceptionsPlugin::checkIeee754ExeptionFlag(4), its
value will change to true at the exact point where the problem
occurred.
In most cases, it won't then be necessary to enable floating point
trapping in order to find the offending line (the other PR that
mysteriously fails under Cygwin on Appveyor).
=> Interface for checking an IEEE754 exception flag in the debugger

include/CppUTest/CommandLineArguments.h, include/CppUTest/TestRegistry.h, include/CppUTest/TestTestingFixture.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, src/CppUTest/CommandLineArguments.cpp, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/TestRegistry.cpp, src/CppUTest/Utest.cpp, tests/CommandLineArgumentsTest.cpp, tests/CommandLineTestRunnerTest.cpp, tests/TestUTestMacro.cpp
this idea is originated from @PaulBussmann, I have this try since Paul seem busy. 
After discuss, it is more reasonable to add one command line to let the `OPTRUN_TEST` get run.
I  currently prefer `OPTRUN_TEST` rather than `OPTIN_TEST` because I think there should only be two possibility, get run then run counted, or get ignored then ignore counted. so, optional run by specifying the command line option `-optRun`
=> argument line option to enable OPTRUN_TEST

appveyor.yml, scripts/appveyor_ci_build.ps1, scripts/appveyor_ci_test.ps1, scripts/appveyor_helpers.ps1
Includes a fix to keep Cygwin working for now.  For some reason it doesn't work on the VS2015 image correctly so can't build with the latest version of visual studio (not that such a configuration was in use anyways).
Also includes a fair amount of cleanup and restructuring of the appveyor scripts to try and reduce the amount of duplication in them and have the variables be more consistent across the different configurations.  Basically, MinGW and Cygwin are now seen as platforms the same as Win32 or x64 is.  PlatformToolset is only to determine the version of the compiler to use.
=> Appveyor cleanup

CMakeLists.txt, cmake/Modules/CppUTestNormalizeTestOutputLocation.cmake, tests/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
A previous 'fix' of mine has CMake hard-coding CppUTest test executables to "${CMAKE_BINARY_DIR}/tests". That's ok when CppUTest is built as the CMake root, but when CppUTest is a component in a more complex project, that path is no longer correct.
This PR changes `cpputest_set_test_output_location` to `cpputest_normalize_test_output_location`, and no longer takes an output path. Instead, the new function simply pushes ${CMAKE_CURRENT_BINARY_DIR} as the build target for all configuration variants, which was the intent of my original clumsy PR.
This is still a WIP so that @jerryryle can see it, please don't merge yet!
=> Fix CMake absolute paths when CppUTest is nested.

src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockCallTest.cpp
=> (#922) MockSupport::expectNoCall does not append scope to function name

include/CppUTestExt/MockActualCall.h, include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCall.h, include/CppUTestExt/MockNamedValue.h, include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockNamedValue.cpp, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockActualCallTest.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockParameterTest.cpp, tests/CppUTestExt/MockReturnValueTest.cpp, tests/CppUTestExt/MockSupportTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp, tests/CppUTestExt/MockSupport_cTestCFile.c
Mock support for bool in C++ only, split from #847.
Note that since the C API does not support bool at all in this version, I have made one additional change: bool parameters and return values are now implicitly convertible to int parameters and return values respectively, and vice versa.  (This only applies to int, not other types such as long or unsigned int.)
This has a consequence that even C++-only tests will pass where the expectation is for a bool and the actual call is an int (or the reverse) -- opinions will probably differ on whether this is a benefit or a drawback, but it was something that I was trying to avoid in the prior PR.
However the main reason this has been done is specifically to allow the case where a C++ test is expecting a bool parameter/return but the actual call …
=> Add mock support for bool (C++ only).

CMakeLists.txt
This will make cmake convert `config.h.cmake` into `generated/CppUTestGeneratedConfig.h` during build and then to `PREFIX/include/CppUTest/CppUTestGeneratedConfig.h` on install, to match the new autotools setup.
I don't know how to make it have an equivalent of `AC_TYPE_LONG_LONG_INT` so `long long` support is still opt-in for cmake.
=> Update cmake builds for new CppUTestGeneratedConfig.h file.

CppUTest.vcproj, CppUTest.vcxproj, include/CppUTest/CppUTestConfig.h, tests/AllTests.vcproj, tests/AllTests.vcxproj, tests/CppUTestExt/IEEE754PluginTest_c.c
Also adds a check for _MSC_VER to disable the FENV logic for versions prior to 2013.  Older versions don't have the fenv.h header file that is required for this to work properly.
This should fix the issue seen in #946.
=> Add IEEE754 files to Visual Studio

Makefile.am, include/CppUTest/TestTestingFixture.h, platforms/Dos/sources.mk, src/CppUTest/CMakeLists.txt, src/CppUTest/TestTestingFixture.cpp, tests/CMakeLists.txt, tests/TestUTestMacro.cpp, tests/TestUTestStringMacro.cpp
Alternative split by splitting out String functions
=> Splitup the Test Macro file, alternative

src/CppUTestExt/IEEE754ExceptionsPlugin.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp, tests/CppUTestExt/IEEE754PluginTest_c.c, tests/CppUTestExt/IEEE754PluginTest_c.h
I'm submitting this despite the Msvc linker failures - @Andne any idea where these might come from?
=> Remove tests for FE_INVALID because not all platforms support this

CppUTest.vcproj, CppUTest.vcxproj, tests/AllTests.vcproj, tests/AllTests.vcxproj
I've added the new source file to the VS201x and VS2005 projects.  I also cleaned up the header files in the VS2005 projects - has no effect on compiling but makes the project cleaner.
VS2013 and VS2015 still fail due to one of the floating point tests.
=> Add missing sources to visual studio

tests/CppUTestExt/IEEE754PluginTest.cpp
Check if any flag is set (rather than all flags), because flags can have different values across compilers and we would prefer not to include <fenv.h> in the tests.
=> Fix failure in Vs 2013 because of Ieee

include/CppUTestExt/IEEE754ExceptionsPlugin.h, src/CppUTestExt/IEEE754ExceptionsPlugin.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp
As discussed in #954, I split the checkIeee754ExeptionFlag(int flag) function into specific functions for each flag.
This allows keeping the specifics of how the flags are defined in the class and avoid anything else depending on fenv.
=> Refactor IEEE754 debugging functions

.gitignore
When using Visual Studio 2015 I noticed that there's a couple new files generated by the IDE containing local information.  I added the extensions for these files to the .gitignore file.
=> Added ignores for VS2015 files

include/CppUTest/SimpleString.h, include/CppUTest/TestFailure.h, include/CppUTest/TestHarness_c.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, src/CppUTest/SimpleString.cpp, src/CppUTest/TestFailure.cpp, src/CppUTest/TestHarness_c.cpp, src/CppUTest/Utest.cpp, tests/SimpleStringTest.cpp, tests/TestHarness_cTest.cpp, tests/TestUTestMacro.cpp
I noticed that CppUTest currently makes no provision for comparing signed byte-sized values. In my experience, in embedded development, sint8_t is frequently used.
This is an attempt at providing the missing functionality.
=> Add interface to compare signed byte-sized data

include/CppUTest/MemoryLeakDetectorNewMacros.h, src/CppUTest/MemoryLeakWarningPlugin.cpp, tests/MemoryOperatorOverloadTest.cpp
=> Included operator delete with size for new gcc

configure.ac
This only takes care of automake. It has not been tested against Gcc 5.3.x.
=> Fix handling of -Wno-c++14-compat

include/CppUTest/CppUTestConfig.h, include/CppUTest/TestHarness_c.h, src/CppUTest/SimpleString.cpp, src/CppUTest/TestHarness_c.cpp, tests/TestFailureTest.cpp, tests/TestHarness_cTest.cpp
And the other int flavours for good measure.
This will have a trivial conflict with #998 if that's merged first but any good merge tool will resolve it automatically.  (Or remind me after merging that and I'll rebase this.)
=> Add CHECK_EQUAL_C_LONGLONG to C TestHarness

include/CppUTest/CppUTestConfig.h, tests/CppUTestExt/MockSupport_cTest.cpp
This patches fixes build failures on armel and m68k that do not seem
to have working FENV support (changes to CppUTestConfig.h).
It also fixes build failures on s390x, ppc64 and sparc64 which
were failing a test due to them being big-endian architectures
(changes to tests/CppUTestExt/MockSupport_cTest.cpp, typeCopy copies
an "int" but the variables param and retval were defined as "long").
Fixes #1004
=> Portability fixes

include/CppUTestExt/MockExpectedCallsList.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCallsList.cpp, tests/CppUTestExt/ExpectedFunctionsListTest.cpp, tests/CppUTestExt/MockParameterTest.cpp
It's been a long time since my last contributions, but I've finally managed to get some free time and I've spend it in finishing the modifications that I started to enable expected calls to match multiple calls. I'm still merging all the changes of the main branch into my outdated code (almost a year full of commits!), but I've detected a bug that I've just fixed, so I'm submitting this standalone PR for it.
Here goes the bug description and fixing notes:
The present code can copy the output parameters of an expected call, but finally fulfill a different one.
This happens for example if an expected call for a function that returns output parameters and ignores other parameters is declared before an expected call for the same function, that also returns expected parameters, but that …
=> Bug fix for wrong output parameters being copied

tests/CppUTestExt/MockSupport_cTestCFile.c
these warnings are treated as errors and thus make the MSVC build fail
fixes #1014
=> fix conversion from double to int

include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCallsList.h, include/CppUTestExt/MockSupport.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockExpectedCallsList.cpp, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/ExpectedFunctionsListTest.cpp, tests/CppUTestExt/MockActualCallTest.cpp, tests/CppUTestExt/MockParameterTest.cpp
As discussed in PR #1018, I submit here some small refactoring changes in preparation for the next modifications.
These modifications don't change or add any functionality, they just rename some methods and attributes, and add a couple of additional methods, in preparation for the actual implementation of multi-matching expected calls.
The key concepts changed are about **matching** actual calls, and **fulfilling** expected calls. 
Until now, an expected call could _match_ a single actual call, and when this _match_ was done, then the expected call was _fulfilled_, so _matching_ and _fulfilling_ was rather the same thing. 
From now on, these two concepts will be separated: During the processing an actual call, expected calls will be able to _match_ it under certain conditions (i.e. …
=> Expected calls matching several actual calls - (1) Preparation

include/CppUTestExt/MockActualCall.h, include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCall.h, include/CppUTestExt/MockExpectedCallsList.h, include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockExpectedCallsList.cpp, src/CppUTestExt/MockFailure.cpp, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockCallTest.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockFailureReporterForTest.cpp, tests/CppUTestExt/MockFailureReporterForTest.h, tests/CppUTestExt/MockStrictOrderTest.cpp
These modifications don't change or add any functionality, they're just simple refactorings that will simplify reviewing subsequent PRs.
They consist in changing the "call order" or "call count" related attributes and methods to use unsigned integers instead of signed integers, renaming a couple of private/internal methods and the optimization of the expected calls list isEmpty() method.
=> Expected calls matching several actual calls - (2) More preparation

CMakeLists.txt, cmake/Modules/CppUTestWarningFlags.cmake
Adds the option `WERROR` to cmake, which will enable `Werror` for C and C++. To maintain compatibility the option is default *OFF*.
_**Related issue:** #1003_
=> Werror as cmake option

scripts/travis_ci_build.sh
Enables `Werror` for CMake based builds on Travis ci.
=> Werror enabled for CMake CI builds

cmake/Modules/CppUTestWarningFlags.cmake
This fixes #991 for **Gcc5** on **CMake** (if C++11 is _enabled_). Because of the CMake flag issue (fixed in #1025), the problem didn't occur earlier for those builds.
As solution, the `-Wno-c++14-compat` flag is added, if C++11 is enabled (as #997 does for autotools).
=> Gcc5 C++14 related issue fixed for CMake

cmake/Modules/FindCXX11.cmake
Visual Studio has a bug where they still report __cplusplus as 199711L
even with a C++11 compatible compiler.
=> cmake: Fix C++11 compatibility detection for Visual Studio

appveyor.yml
Hopefully this fixes the issues we've seen with the appveyor build reliability (such as #1016).  I added the install folders to the appveyor cache so that it stores them between builds.  That way the install is already done and doesn't have to download MinGW, which is where the failure seemed to occur.  If appveyor.yml changes, then the cache is invalidated, since the version of MinGW used is defined in appveyor.yml.
Only part I don't quite like are the yellow messages about missing folders to cache.
=> Use Appveyor cache for MinGW

src/CppUTest/SimpleString.cpp
Clang 3.9 warning fixed.
<sub>**Travis CI fails:** #1034</sub>
=> Clang 3.9 warning fixed

cmake/Modules/CppUTestWarningFlags.cmake
Adds `-pedantic` to C and C++ flags on CMake builds.
_**Note:** Build failures are related to #1034._
=> Pedantic flag added to CMake

platforms/iar/CppUTest.ewp, platforms/iar/CppUTestTest.icf
Added some missing references in the IAR platform. Also increased the flash size in the CppuTestTest project as I got an out of memory error from the linker. Now running fine on EWARM 7.50.3.10751.
=> Fix for IAR project

include/CppUTest/MemoryLeakDetectorMallocMacros.h, include/CppUTest/MemoryLeakDetectorNewMacros.h, src/CppUTest/TestHarness_c.cpp
- Renamed strlen function implemented in TestHarness_c;
- Created advanced inclusion control of strdup and strndup macros to avoid conflicts.
=> Fixing OSX build conflicts with strdup and strndup

examples/AllTests/FEDemoTest.cpp, include/CppUTest/CppUTestConfig.h, src/CppUTestExt/IEEE754ExceptionsPlugin.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp
The solution was in code using preprocessor conditionals, because there was already those conditionals there, so I just expanded a little. 
It is not the best solution because it may mislead code coverage, ideally we should select in the build the presence or not of the plugin, but it broke the examples, so I rolled back to the preprocessor solution.
=> Removing IEEE754 implementation from Mac OSx

src/CppUTestExt/MockNamedValue.cpp, tests/CppUTestExt/MockNamedValueTest.cpp
These changes fix a bug in CppUMock where copiers are not installed correctly (especially when used with the MockSupportPlugin)
=> Install copier correctly

src/CppUTest/MemoryLeakWarningPlugin.cpp, tests/CppUTest/MemoryLeakWarningTest.cpp
Fixes the failure case caused by this simple test program:
```
#include <iostream>
#include <algorithm>
#include <vector>
#include <CppUTest/CommandLineTestRunner.h>
#include <CppUTest/TestHarness.h>
TEST_GROUP(HelloWorld)
{
};
TEST(HelloWorld, OnlyTest)
{
std::vector<int> v{0, 0, 3, 0, 2, 4, 5, 0, 7};
std::stable_partition(v.begin(), v.end(), [](int n){return n>0;});
for (int n : v) {
std::cout << n << ' ';
}
std::cout << '\n';
}
int main(int argc, char** argv)
{
return CommandLineTestRunner::RunAllTests(argc, argv);
}
```
=> Add nothrow delete operator variant overload.

platforms/Eclipse-Cygwin/README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

src/CppUTest/SimpleString.cpp, tests/CppUTest/SimpleStringTest.cpp
For undersized buffers, the current implementation of SimpleString::copyToBuffer will attempt to set the null terminator outside of the buffer bounds.  I've added a unit test for undersized buffers and modified the implementation to pass.  Additionally, all other tests continue to pass.
Also, I'd like to thank you for this great framework.
=> Fixed SimpleString::copyToBuffer handling of undersized buffers

src/CppUTest/CMakeIntegration-README.md, src/CppUTest/CMakeLists.txt
I have made the following changes:
* add a section to declare the include folder as a PUBLIC property. This means that any project depending on this CMakeLists.txt would automatically inherit the include folder.
```cmake
target_include_directories(CppUTest
PUBLIC
../../include
)
```
* use a relative path for referring to include. This removes the need for an external definition of the variable CppUTestRootDirectory.
* remove `STATIC` from ```add_library(CppUTest STATIC ${CppUTest_src} ${CppUTest_headers})```. There is no need to be specific about building a STATIC library. The enclosing project could choose alternatives to static linking.
* remove the unconditional addition of `../Platforms/${CPP_PLATFORM}/UtestPlatform.cpp` to the sources that get compiled into the CppUTest library. It …
=> allow building CppUTest as a sub-project of a cross-platform application (fixes #1102)

include/CppUTest/TestHarness_c.h, tests/CppUTest/TestHarness_cTest.cpp, tests/CppUTest/TestHarness_cTestCFile.c
I'd like to set native C tests to be ignored to have the same behavior as the C++ macro. I created two (IGNORE_TEST_C_WRAPPER and IGNORE_TEST_C) to be explicit whether you're looking at the C test or the Cpp wrappers.
In looking at the tests for the current IGNORE_TEST macro, there were a lot that tested whether or not other macros could work inside the test. Are those needed here? Since we are wrapping around the normal IGNORE_TEST macro, it seems like that has already been covered. The only thing left is to use it (which is what I've done.)
=> Create an equivalent IGNORE macro for C-only code

src/CppUTest/TestOutput.cpp, tests/CppUTest/TestOutputTest.cpp
If you run a test set with "-r#", the progress indicator dots don't line up from
one run to another. It makes it difficult to look for differences when the output
is different every time even though the tests run the same.
=> Reset dotCount_ to align progress indicators for repeat runs

include/CppUTest/TestFailure.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h, src/CppUTest/TestFailure.cpp, src/CppUTest/Utest.cpp, tests/CppUTest/TestUTestMacro.cpp
Hi,
I've taken a shot at implementing the `CHECK_RELATION()` macro described in #8.
On failure, the following kind of message will be shown in the output:
```
/Users/dlindelof/Work/cpputest/tests/CppUTest/TestUTestMacro.cpp:400: error:
Message: evaluates to 0.5 >= 0.8
CHECK(actual >= minimum) failed
```
Please let me know if this is something you still think could be useful.
=> define CHECK_RELATION() macro

appveyor.yml, tests/CppUTest/UtestTest.cpp, tests/CppUTestExt/IEEE754PluginTest_c.c
Visual C++ detects the divide by zero at compile time unless the variables are volatile.  This fixes one of the warnings reported in #1079.
Changing the build image was needed in order to keep the MinGW32 build working. It's not a permanent fix, but I'm not sure what will be yet.
=> Fix float warning

CMakeLists.txt, appveyor.yml, cmake/Modules/CppUTestConfigurationOptions.cmake, scripts/appveyor_ci_build.ps1, scripts/appveyor_ci_test.ps1, scripts/appveyor_helpers.ps1, scripts/travis_ci_build.sh
Fixes #1120 
I finally found a more permanent fix than using the old image on appveyor.  By forcing static linkage I'm able to get the right set of libraries to be used and avoid any funny conflicts in the exception handling.  Now all of the appveyor builds are working properly again and should continue to as they update software more.
At present I've only applied my fix when running under MinGW, since the version of CMake on travis-ci is so old, I'm unable to tell if any changes need to be made there as well.
=> Fix MinGW 32-bit crashes on appveyor, some minor CMake cleanup too

CppUTest.vcxproj, CppUTest_VS201x.sln, appveyor.yml, tests/AllTests.vcxproj, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/TestUTestMacro.cpp
This is my take at what was being done in #1122.  Most of the fixes are just unsetting the most-significant bit/byte of the constant so that sign-extension doesn't need to be performed.  The SimpleString tests were fixed by assuming that `long long` always exists on 64-bit, so therefore a test that had two different forms depending on `sizeof(long)` didn't need to have the two forms anymore.
I've also added the x64 build to Appveyor.  It only seems to work on v140 (VS2015) for some reason, the v100 (VS2010) build gets an error about missing winmm.lib.  I suspect there may be an issue with the install on Appveyor, I do not get that error locally.  Also, the warnings that are being fixed don't appear on v100 anyways.
@andrew-elder Take a look at this, does it fix things for you?
=> Fix warnings on x64, add to appveyor

tests/CppUTest/AllocLetTestFree.c, tests/CppUTestExt/MockCheatSheetTest.cpp
=> Clang Static Analyzer - "dead assignment" warning fixes

tests/CppUTest/TestMemoryAllocatorTest.cpp
Another partial fix for issue #1126.
=> Clang Static Analyzer - "uninitialized argument value" warning fix

CMakeLists.txt
This pull request adds a new top-level option for CppUTest's CMake configuration that controls whether the verbose configuration text is printed during CMake's project generation phase.
The option is `VERBOSE_CONFIG`, and it is set to ON by default, preserving the current behavior.
If `-DVERBOSE_CONFIG=OFF` is passed to CMake, the configuration banner will not be printed.
(When generating multiple CMake configurations in parallel that all pull in CppUTest, the subsequent message output race conditions print a screen full of well-intended gibberish, so this gives users the option to silence it)
=> Add CMake option for quieter configuration

include/CppUTestExt/MockNamedValue.h, include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockNamedValue.cpp, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockComparatorCopierTest.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockSupportTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp
Differentiated const and non-const objects used as aux data stored by MockSupport.
BTW, this PR avoids the necessity to perform const casts that are not liked by clang (see #1137 discussion).
=> Differentiated const and non-const objects

include/CppUTestExt/MockCheckedExpectedCall.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, tests/CppUTestExt/MockCallTest.cpp
With this modifications, if onObject() is called on a expected call, it is considered that the expectation matches only the specific object passed; but if it's not called, it's considered that the expectation matches any object.
Therefore, when onObject() is called on an actual call, both the expectations that target the passed object and the expectations that do not target a specific object will match.
This is a solution for #1019.
=> Made expectation objects optional.

src/CppUTestExt/MockNamedValue.cpp
The integer comparisons between signed and unsigned values did not
always verify that the signed integer was positive before comparing it
to an unsigned type. This is problematic since it could cause an
unsigned integer to match its 2s complement signed equivalent.
Additionally, the signed comparisons were using incorrect type casts.
Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>
=> add positive checks and fix typecasts for integer comparisons

src/Platforms/Iar/UtestPlatform.cpp
Remove the newline character after the date and time in the JUnit output on IAR platform.
=> IAR: Fix spurious newline after time in JUnit output.

src/CppUTest/JUnitTestOutput.cpp, tests/CppUTest/JUnitOutputTest.cpp
Add a newline at the end of each JUnit output file so the file ends with a newline character.
=> Add newline to end of JUnit output files.

build/MakefileWorker.mk, examples/AllTests/EventDispatcherTest.cpp
Add -Wno-reserved-id-macro and -Wno-keyword-macro to clang builds. Fixes CppUTest on Xcode 7+, with clang-700+, where warnings were added about using reserved namespaces like __, and for macros that shadow keywords. Also, make it future proof.
Remove warning, cast from 'const void *' to 'Event *' drops const qualifier in examples/AllTests/EventDispatcherTest.cpp file.
=> Fix CppUTest for OSX / Xcode9 / clang-900.x or any newer version

include/CppUTest/SimpleString.h, src/CppUTest/SimpleString.cpp, tests/CppUTest/SimpleStringTest.cpp
In C++11, the nullptr_t type was introduced, and in some projects NULL
is defined as nullptr. In this case, the C++ compiler will produce
warnings when trying to convert NULL to a string, because it is
ambiguous which conversion is used.
test.cpp:89:2: error: call to 'StringFrom' is ambiguous
CHECK_EQUAL(NULL, actual);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/CppUTest/UtestMacros.h:127:3: note: expanded from macro 'CHECK_EQUAL'
CHECK_EQUAL_LOCATION(expected, actual, NULL, __FILE__, __LINE__)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/CppUTest/UtestMacros.h:138:52: note: expanded from macro 'CHECK_EQUAL_LOCATION'
UtestShell::getCurrent()->assertEquals(true, StringFrom(expected).asCharString(), StringFrom(actual).asCharString(), text, file, …
=> add StringFrom for std::nullptr_t values

src/CppUTest/TeamCityTestOutput.cpp, tests/CppUTest/TeamCityOutputTest.cpp
When using Teamcity output, we encountered ill formatted output due to missing escapes in testnames. This Patch always outputs "user defined messages" escaped
=> Print test names and test group names escaped when using teamcity

scripts/README.txt
I fixed a typo from 'TTDing' to 'TDDing'.
=> Fix typo of scripts/README.txt

CMakeLists.txt
It would be a nice feature to be friendly with Conan.
It allows to propagate easily flags for:
- C++ language standard
- ABI (ABI incompatibility between GCC version)
- runtime libraries with Visual Studio
- and so on...
@bryceschober is kindly managing a repository to host the conan recipe for CppUTest.
While trying to set up a CI on AppVeyor, he met a lot of link issues related to runtime incompatibility (https://github.com/bryceschober/conan-cpputest/issues/5).
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\link.exe /ERRORREPORT:QUEUE /OUT:"C:\projects\conan-cpputest\test_package\build\39d1509292314c21074b4137bae955683dd6acf9\bin\example.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:C:/Users/appveyor/.conan/data/CppUTest/master/bryces …
```
=> [cmake] add support for Conan, a C++ package manager

Makefile.am, include/CppUTest/UtestMacros.h, include/CppUTestExt/MockActualCall.h, include/CppUTestExt/MockCheckedActualCall.h, include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCall.h, include/CppUTestExt/MockNamedValue.h, include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockNamedValue.cpp, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockActualCallTest.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockFakeLongLong.cpp, tests/CppUTestExt/MockParameterTest.cpp, tests/CppUTestExt/MockReturnValueTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp, tests/CppUTestExt/MockSupport_cTestCFile.c
When testing code that needs to work on both 64-bit platforms and 32-bit
platforms, the long integer may not guarantee 64bits of width on the
32-bit platform. This makes testing calls which take and return 64bit
values difficult, as the test framework can't handle these natively.
Add support for long long integers, so that test code can natively
handle these larger values.
Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>
=> add support for long long integers as native types

include/CppUTestExt/MockSupport.h, src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockCallTest.cpp
MockSupport::expectNoCall() now uses a multi-matching expected call with zero expected calls, thus avoiding the usage of a dedicated list to keep track of "unexpectations" and therefore simplifying the architecture of the MockSupport class.
=> Simplified MockSupport::expectNoCall() method implementation.

scripts/templates/ProjectTemplate/Project.cproject
With this change if you have the CPPUTEST_HOME environment variable set, then the include paths for the eclipse project will use this value if not it will try using the upper directory.
=> Use CPPUTEST_HOME env variable for eclipse project include path

include/CppUTest/SimpleString.h, src/CppUTest/SimpleString.cpp
=> Fix: avoid using std::nullptr_t with ARM C++11 compiler

include/CppUTest/TestHarness_c.h, src/CppUTest/TestHarness_c.cpp, tests/CppUTest/TestHarness_cTest.cpp
Adds for all C-Interface assertions a <assertion>_TEXT macro variant using the existing functionality.
=> Add _TEXT assertions to C-Interface

README.md
The present ReadMe Getting Started instructions do not indicate that a new build directory needs to be created by the user.  autoget.sh should be run in the root of the project, whereas the configure command needs to be run in a sub-directory.  Expand the instructions to show creating and navigating to a build directory and then markup commands.
=> State Need For Manual "build directory" In ReadMe

.travis.yml
Due the current Linux infrastructure migration the `sudo: false` option has been deprecated. Please visit the [announcement](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration) for more details.
=> Deprecated travis option removed

include/CppUTest/StandardCLibrary.h
If memory leak detection for C code is enabled, the header file
MemoryLeakDetectorMallocMacros.h is included by the command line prior
to any of the raw source code for an object.
In this case, if CPPUTEST_HAVE_STRDUP is defined, the strdup function
will be redefined using a macro.
If the source code happens to include <string.h> or <cstring>, this will
happen *after* the memory leak detection header is included on the
command line.
Because of this, strdup will have already been redefined, and will then
result in compiler warnings similar to the following:
/usr/include/string.h:166:37: error: expected identifier before string constant
extern char *strdup (const char *__s)
^
/usr/include/string.h:166:37: error: expected ‘,’ or ‘...’ before string constant
In file included from …
=> include string.h in StandardCLibrary.h

include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCall.h, include/CppUTestExt/MockNamedValue.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockNamedValue.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockNamedValueTest.cpp, tests/CppUTestExt/MockParameterTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp, tests/CppUTestExt/MockSupport_cTestCFile.c
Added overloaded methods for withParameter and withDoubleParameter which takes a tolerance as well as the expected value for doubles
=> Added support for setting tolerance for doubles in mock

README.md, include/CppUTest/UtestMacros.h, tests/CppUTest/TestUTestMacro.cpp
Scoped enumerations from C++11 are no implicit
conversions from their values to integral types.
Add two assertion macros.
ENUMS_EQUAL_INT(excepted, actual)
Compares two enums which their underlying type is int
ENUMS_EQUAL_TYPE(underlying_type, excepted, actual)
Compares two enums which they have the same underlying type
=> Add scoped enum support

src/Platforms/VisualCpp/UtestPlatform.cpp
Support Microsoft UWP platform by providing an alternative timer function in ```VisualCppTimeInMillis()``` due to absence of ```timeGetTime()``` API in UWP.
```TIMERR_NOERROR``` can be used to detect presence of timeGetTime() API.
UWP supports ```QueryPerformanceFrequency()/QueryPerformanceCounter()``` API which can be used for time calculation and this API is available on all Windows versions, so the proposal is to use this implementation for Windows platform in general and fallback to ```timeGetTime()``` or ```GetTickCount``` in case ```QueryPerformanceFrequency()``` fails due to some unknown reason.
```timeGetTime()``` also suffers from lower time resolution  which can be avoided by new implementation too.
=> Support Microsoft UWP platform by extending VisualCppTimeInMillis().

src/CppUTest/CMakeLists.txt
Added Shuffle.h and SimpleMutex.h in the list of headers to be installed in CMakeLists.txt.
=> Added missed header files when cpputest is being installed as external project though cmake

README.md
The CPPUTEST_HOME variable to be added to CPPFLAGS perhaps needs to be prefixed with a $ to work in a Makefile.
=> In README: CPPUTEST_HOME variable prefixed with a $

include/CppUTest/Shuffle.h, include/CppUTest/TestRegistry.h, include/CppUTest/Utest.h, src/CppUTest/TestRegistry.cpp, src/CppUTest/Utest.cpp
Signedness correction (reported by clang 8).
@basvodde isn't `size_t` a better choice here anyway? Neither test count nor `shuffle_list()` parameter should become `< 1`.
=> Signedness corrected

include/CppUTest/JUnitTestOutput.h, src/CppUTest/JUnitTestOutput.cpp, src/CppUTest/SimpleString.cpp, tests/CppUTest/JUnitOutputTest.cpp
This change extends escaping of XML special characters to text blocks as well
as attributes.  It also changes the mapping to use standard escape encoding:
"   &quot;
<   &lt;
>   &gt;
&   &amp;
This change maintains the historic behavior of mapping newlines to "{newline}"
in the XML text. We're not sure whether this is optimal for Bamboo and Jenkins,
although our experience to date is it's better then emitting the raw newlines
or mapping newlines to spaces.
This implementation is expensive, calling SimpleString::replace() repeatedly
over the same string.  The cost was mitigated by modifying the replace() method
to exit quickly if the pattern is not found.
=> JUnit output: Encode special chars in XML Text

include/CppUTest/MemoryLeakWarningPlugin.h, include/CppUTest/TestPlugin.h, include/CppUTest/UtestMacros.h, src/CppUTest/JUnitTestOutput.cpp, src/CppUTest/MemoryLeakWarningPlugin.cpp, src/CppUTest/TestFailure.cpp, src/CppUTest/TestTestingFixture.cpp, src/CppUTestExt/MockActualCall.cpp, tests/CppUTest/SetPluginTest.cpp, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/TestHarness_cTest.cpp, tests/CppUTest/TestUTestMacro.cpp, tests/CppUTest/TestUTestStringMacro.cpp, tests/CppUTestExt/CodeMemoryReporterTest.cpp, tests/CppUTestExt/MemoryReportFormatterTest.cpp, tests/CppUTestExt/MemoryReporterPluginTest.cpp, tests/CppUTestExt/MockCallTest.cpp, tests/CppUTestExt/MockParameterTest.cpp, tests/CppUTestExt/MockPluginTest.cpp
Empty expression warnings fixed (#1206).
Together with #1205 this concludes the Clang 8 support.
=> Empty expression warnings fixed

Makefile.am
Autotools-generated makefile now installs Shuffle.h, which was
previously omitted, causing failures when compiling tests.
=> Add Shuffle.h to autotools install

CMakeLists.txt, CppUTestConfig.cmake.install.in, cmake/Modules/CppUTestBuildTimeDiscoverTests.cmake, cmake/Scripts/CppUTestBuildTimeDiscoverTests.cmake, src/CppUTest/CMakeLists.txt, src/CppUTestExt/CMakeLists.txt
This PR enables CppUTest lib clients to use the CMake `cpputest_buildtime_discover_tests()` function with the benefit of the CMake generated project/solution that autodiscovers tests.
To use buildtime discover on your tests add the following to your test project CMakeLists.txt
```cmake
cpputest_buildtime_discover_tests(<TestName>)
```
1. CppUTest is configure using CMake, build and installed
2. CMake based test project
A CMake base test project with a top level `CMakeLists.txt` that includes:
```cmake
include(CTest)
enable_testing()
FIND_PACKAGE(CppUTest REQUIRED CONFIG)
```
An implementation that you want to test e.g. `src/CMakeLists.txt`:
```cmake
add_library(MyModule  MyModule.c)
``` 
And a  test e.g. `tests/CMakeLists.txt` with discovery added :
```cmake
add_executable(TestMyModule …
```
=> Enable cmake buildtime discover tests for CppUTest clients.

include/CppUTest/TestOutput.h, include/CppUTest/Utest.h, include/CppUTest/UtestMacros.h
This fixes a handful of pedantic compiler and static analysis warnings.
=> Fix missing class member function override specifiers

cmake/Modules/CppUTestWarningFlags.cmake
Disables the `no-inconsistent-missing-destructor-override`, which fail the clang builds atm.
This follows the [C++ Core Guidelines (C.128)](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-override) which recommend _not_ to add `override` to dtors.
=> Fix for inconsistent-missing-destructor-override warning

.gitattributes
Fixes : "AC_CONFIG_MACRO_DIR([m4]) conflicts with ACLOCAL_AFLAGS=-I m4" error.
This was required for `autoreconf -i` for WSL Ubuntu 18.04
=> Force line endings to fix libtoolize error.

include/CppUTest/CppUTestConfig.h
Here is an excerpt from "MULTI Compiler 2017.1 Release Notes for Embedded 68K/ColdFire":
Changes in fenv.h:
The fenv.h header file no longer defines the floating-point exception macros
FE_DIVBYZERO, FE_INEXACT, FE_INVALID, FE_OVERFLOW, and FE_UNDERFLOW.
In addition, the FE_ALL_EXCEPT macro is now defined as 0. This change more
clearly indicates the compiler's lack of support for floating-point exceptions.
=> Remove floating point support for GreenHills compiler on the Coldfire processor

include/CppUTest/CppUTestConfig.h, include/CppUTestExt/MockCheckedActualCall.h
GreenHills is sensitive to the location of the "override" specifier on methods that return function pointers. This fix was tested with Visual Studio 2017 and GreenHills 7.1.4 on ColdFire.
An example of the error previously produced follows:
```
[  6%] Building CXX object src/CppUTestExt/CMakeFiles/CppUTestExt.dir/MockSupportPlugin.cpp.o
"N:/cpputest/include/CppUTestExt/MockCheckedActualCall.h", line 216: error #65:
expected a ";"
virtual void (*returnFunctionPointerValue())() _override;
```
Interestingly, GreenHills did compile with the following placement of override:
```
virtual void (*returnFunctionPointerValue() _override )();
```
but that broke Visual Studio leading me to avoid use of "override" on GreenHills.
=> Fix issue where GreenHills is not fully compatible with "override" specifier

src/CppUTest/Utest.cpp, tests/CppUTest/TestUTestMacro.cpp
This Pull request ignores nullpointers when comparing between memory regions with size 0
=> Allow nullpointers in Memory comparer when comparison size is zero

.travis.yml, scripts/travis_ci_build.sh
Travis updated to the latest bionic image.
This caused the non-C++11 CMake clang build to fail because of  warnings:
* -Wc++98-compat
* -Wc++98-compat-pedantic
* -Winconsistent-missing-destructor-override
Since all three are only disabled with `C++11=ON` it failed to compile on clang with C++11 disabled.
While it makes sense to disable the last one somehow, I'm not that sure about the C++98 compat.
Other options:
1. Disable the C++98 warnings only for clang
1. Set C++98/03 explicitly
=> Travis image update and C++98 compat warnings

README.md
"Example Test" is missing semicolon after TEST_GROUP. Adding semicolon to example.
=> Correcting Example in README.

src/CppUTest/CommandLineTestRunner.cpp, tests/CppUTest/CommandLineTestRunnerTest.cpp
If command line arguments parsing fails, return non-zero from CommandLineTestRunner::RunAllTests.
Fixes #1243
=> Return non-zero for command line errors

include/CppUTest/MemoryLeakDetectorNewMacros.h, src/CppUTest/MemoryLeakWarningPlugin.cpp, tests/CppUTest/MemoryOperatorOverloadTest.cpp
Another approach to #991 by including these operators only when compiling C++14 or newer. This version does not depend on any build system.
=> Gcc 5 c++14-compat warning  - std check

src/CppUTest/MemoryLeakDetector.cpp
Unsigned comparison corrected (fixes #1231).
=> Unsigned comparison

include/CppUTest/SimpleString.h
Not 100% sure if this is really necessary, but I had some problems compiling without the std so I thought it might do no harm
=> nullptr is defined in Std namespace

src/CppUTest/SimpleString.cpp
Replaces the GNU `__attribute__((unused))` with a simple cast to void which should be portable on all systems.
=> Extension attribute replaced

src/CppUTest/SimpleString.cpp
This fixes compiling cpputest with CMake and MinGW-w64.
The compilation used to fail with:
```
src/CppUTest/CMakeFiles/CppUTest.dir/SimpleString.cpp.obj
C:\git\tdd\cpputest\src\CppUTest\SimpleString.cpp:565:31: error:
'nullptr_t' does not name a type
SimpleString StringFrom(const nullptr_t value)
^~~~~~~~~
C:\git\tdd\cpputest\src\CppUTest\SimpleString.cpp:565:31: note: 'nullptr_t'
is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
C:\git\tdd\cpputest\src\CppUTest\SimpleString.cpp:32:1:
+#include <cstddef>
C:\git\tdd\cpputest\src\CppUTest\SimpleString.cpp:565:31:
SimpleString StringFrom(const nullptr_t value)
^~~~~~~~~
C:\git\tdd\cpputest\src\CppUTest\SimpleString.cpp:565:14: error:
redefinition of 'SimpleString StringFrom(int)'
SimpleString StringFrom(const …
```
=> Added namespace directive to fix compilation error under MinGW-w64.

include/CppUTest/JUnitTestOutput.h, src/CppUTest/JUnitTestOutput.cpp, tests/CppUTest/JUnitOutputTest.cpp
If JUnit package is set, add it to the report file name.
Slightly expand list of special characters not allowed in file names
as package is provided via command line.
Closes #1256
=> Add package to JUnit report file name

src/CppUTest/Utest.cpp, src/Platforms/Gcc/UtestPlatform.cpp, tests/CppUTest/UtestPlatformTest.cpp
- Treat any non-zero return from child process as failure (fixes #1211).
- Fix waiting for test in separate process under debugger by not checking uninitialized status variable (happens when continue checks loop condition).
- Count tests run in separate process as 'run' if fork() succeeds (fixes #1210).
=> Fix GCC platform-specific error cases for -p flag

include/CppUTest/TestResult.h, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/TestOutput.cpp, tests/CppUTest/CommandLineTestRunnerTest.cpp, tests/CppUTest/TestOutputTest.cpp, tests/CppUTest/TestResultTest.cpp
* Add helper function to `TestResult`
* Make `TestOutput` report error based on it
* Make `runAllTests()` return non-zero based on it
Fixes #1262
=> Return failure if no tests are run or ignored

configure.ac
Weird behavior with some autotools in Debian caused the default directories to be different. Adding the additional configuration flag fixes that.
=> Fix weird behavior of Debian docker image's autotools

tests/CppUTestExt/MockFakeLongLong.cpp
Define the macro in the #ifdef so that it is not unused when there is no define defined.
=> Removed unused macro warning

Makefile.am, platforms/Dos/sources.mk, tests/AllTests.vcproj, tests/AllTests.vcxproj, tests/CppUTest/CMakeLists.txt, tests/CppUTest/DummyMemoryLeakDetector.cpp, tests/CppUTest/DummyMemoryLeakDetector.h, tests/CppUTest/MemoryLeakWarningTest.cpp
Extracted the DummyMemoryLeakDetector to be in a separate file. This cleans up the test a bit and it also ought to help with the Watcom build that is continuously failing.
=> Extracted the DummyMemoryLeakDetector

README.md
A view improvements:
- Git tag changed to *master*, v3.8 is really outdated
- `file(GLOB_RECURSE ...)` [should not be used for collecting source files](https://cmake.org/cmake/help/latest/command/file.html#glob-recurse)
- `target_link_libraries()` will automatically propagate include paths and link libraries
=> CMake example in the readme improved

include/CppUTest/SimpleString.h, src/CppUTest/SimpleString.cpp, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/UtestPlatformTest.cpp
Linux build with -no-std-lib was broken. It cannot find nullptr.
=> Added #if for compilation with -no-libc

Makefile.am, configure.ac, src/CppUTest/SimpleString.cpp
Support for C++98, which also fixed the GTest1.5 build.
=> Support for C++98

src/Platforms/Dos/UtestPlatform.cpp
Adds the platform specific rand and srand functions for DOS.
Mainly for fixing the broken DOS CI build – which still fails, but now with mem leak test failures.
=> rand / srand for DOS platform

src/CppUTestExt/MockSupport.cpp
Just fixing a typo in this constant name.
=> Fix typo: scopeFunctionName

include/CppUTestExt/MockCheckedExpectedCall.h, include/CppUTestExt/MockExpectedCall.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockExpectedCall.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockFailureTest.cpp, tests/CppUTestExt/MockParameterTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp
When writing mock expectations, a mock implementation may have an output
parameter. In some tests it may be that the output parameter remains
unmodified.
To write an expectation which has an output parameter that is unmodified
you can use the following code:
.withOutputParameterReturning("name", NULL, 0)
This is somewhat confusing, so add a shorthand
.withOutputParameter("name")
This sets up the mock function to expect the "name" output parameter but
leave it unmodified.
=> add .withOutputParameter to expected call

src/Platforms/Iar/UtestPlatform.cpp
Ad the possibility to output strings that are normally written to a file to stdout. This makes it possible to generate JUnit XML output with the IAR simulator or even real HW. All FPuts are redirected to stdout and prepended with "FILEx" where x is an incrementing number. This makes it possible to separate the output later to different files.
Small caveat: All FPuts must be terminated with a newline character and should not contain newline characters except for the terminating one.
=> IAR: Add support to redirect file writes to stdout.

src/CppUTest/MemoryLeakWarningPlugin.cpp, tests/CppUTest/MemoryLeakWarningTest.cpp
EXPECT_N_LEAKS() can't be supported when CppUTest is configured with --disable-memory-leak-detection, since there's nothing to make sure we hit the expected number of leaks.
In one sense, it would be nice for tests that use EXPECT_N_LEAKS() to go ahead and continue running with whatever capabilities CppUTest is configured with.  This change would allow that behavior.
But on the other hand, I guess someone that really expected leaks might want to see the failure to know that CppUTest wasn't configured like they expected.
Is the intended behavior for tests using EXPECT_N_LEAKS() to fail when CppUTest is configured with --disable-memory-leak-detection, or was this just a miss? Thoughts?
=> Disable EXPECT_N_LEAKS() if memleak detection disabled

docker/Dockerfile.dos, docker/Dockerfile.gcc10, docker/Dockerfile.ubuntu
Dockerfile RUN statements improved to avoid unnecessary layers and prevent apt issues (see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/).
=> Run statements cleanup

README.md
Example updated to use `latest-passing-build` instead of `master`.
=> Git ref of the cmake example updated

CMakeLists.txt, appveyor.yml, cmake/clang+mingw-win32.toolchain.cmake, cmake/clang+mingw-win64.toolchain.cmake, scripts/appveyor_ci_build.ps1, scripts/appveyor_helpers.ps1
The workaround to fix CMake + MinGW compilation breaks CMake + Clang + MinGW bintools compilation, so it's fixed to apply only if the compiler is not Clang (for some dark reason CMake flags Clang as a MinGW compiler).
Besides that I've added a couple of toolchain files for CMake to simplify using this toolchain combination, and added it to CI builds.
=> Fixed compilation using CMake with Clang + MinGW bintools in Windows

CMakeLists.txt, examples/AllTests/CMakeLists.txt, examples/CMakeLists.txt, tests/CppUTest/CMakeLists.txt
Moves `enable_testing()` to the project source root directory as mentioned in the [docs](https://cmake.org/cmake/help/latest/command/enable_testing.html).
Starting from v3.15 the documentation explicitly mentions that it's _"automatically invoked, when CTest module is included"_. Earlier version may do that too, but since the minimum version is v3.1 I kept the `enable_testing()` call, just be be safe.
=> enable_testing() moved to project source root directory

cmake/Modules/CppUTestConfigurationOptions.cmake
Compiler extensions disabled on the CMake build (see [docs](https://cmake.org/cmake/help/latest/prop_tgt/CXX_EXTENSIONS.html)). This ensures the build pure standard and prevents eg. the usage of gnu extensions.
@basvodde what's your opinion on unconditionally set this option? Or alternatively, set it to `OFF` unless it's already set to `ON` (eg. option explicitly passed).
=> Compiler extensions disabled

include/CppUTest/SimpleString.h, include/CppUTest/TestMemoryAllocator.h, include/CppUTestExt/MockCheckedActualCall.h, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/MemoryLeakDetector.cpp, src/CppUTest/SimpleString.cpp, src/CppUTest/TestMemoryAllocator.cpp, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockSupport.cpp, tests/CppUTest/AllTests.cpp, tests/CppUTest/CommandLineTestRunnerTest.cpp, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/TestMemoryAllocatorTest.cpp, tests/CppUTest/UtestPlatformTest.cpp, tests/CppUTestExt/AllTests.cpp, tests/CppUTestExt/ExpectedFunctionsListTest.cpp, tests/CppUTestExt/MockActualCallTest.cpp, tests/CppUTestExt/MockExpectedCallTest.cpp, tests/CppUTestExt/MockFailureReporterForTest.cpp, tests/CppUTestExt/MockFailureReporterForTest.h, tests/CppUTestExt/MockFailureTest.cpp, tests/CppUTestExt/MockSupportTest.cpp
Finally.
Had to kill all the static SimpleString's to avoid weird deallocations. This also now resolves the memory leaks in CppUTest when using C. It uses longjump and couldn't deallocate the strings. Now it can.
=> Using the SimpleStringCache

include/CppUTest/CppUTestConfig.h, tests/CppUTest/MemoryLeakWarningTest.cpp, tests/CppUTest/MemoryOperatorOverloadTest.cpp
will turn off memory leak checker automatically
=> Address sanitizer on clang linux 

tests/CppUTest/UtestTest.cpp
Fixes the _"zero as null pointer constant"_ warning, when compiling with Clang 5:
```
/mnt/tests/CppUTest/UtestTest.cpp:441:11: error: zero as null pointer constant
[-Werror,-Wzero-as-null-pointer-constant]
CHECK(NULL == tests.getFirstTest());
^~~~
nullptr
/usr/include/clang/5.0.2/include/stddef.h:100:18: note: expanded from macro
'NULL'
^
```
=> zero as null pointer warning fixed

src/CppUTest/CMakeLists.txt
Fixes the missing `SimpleString.h` header file error, when compiling tests with CMake.
=> Missing SimpleString.h fixed

CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
Adds an option `TESTS_BUILD_DISCOVER` (default: `ON`) to disable build time discover of tests, see #1144.
=> Option for build discover of tests

cmake/Modules/CppUTestConfigurationOptions.cmake, gcovr.cfg, scripts/travis_ci_build.sh
As mentioned in #1139.
@basvodde I used [gcovr](https://github.com/gcovr/gcovr) instead of lcov as it's much easier to install and use. It can create coverage results, reports in various formats etc. in a single pass and provides support for configuration file. If the the lcov is still set, can migrate it back.
Should I change the make target to `check_coverage` as used in `Makefile.am`? Would keep it consistent.
=> CMake coverage report generation

CMakeLists.txt
From https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html:
Note: Call the cmake_minimum_required() command at the beginning of the top-level CMakeLists.txt file even before calling the project() command. It is important to establish version and policy settings before invoking other commands whose behavior they may affect. See also policy CMP0000.
For instance, if cmake_minimum_required is called from within the project, I am unable to build the project with `cmake .. -DCMAKE_POLICY_DEFAULT_CMP0091=NEW` because the global policy scope is overwritten with the more specific project policy scope.
=> Call cmake_minimum_required() before project() in CMakeLists.txt.

include/CppUTest/UtestMacros.h, tests/CppUTest/TestUTestMacro.cpp
These are useful when working with error code return values, where one
often compares to zero which means no error has happened.
=> Add CHECK_EQUAL_ZERO macros

include/CppUTest/SimpleString.h, include/CppUTest/StandardCLibrary.h
Doing so might cause conflict with the memory macros.
Moves the <string> include to the right place.
=> Should not do Standard library includes outside the StandardCLibrary/h

include/CppUTest/SimpleString.h, include/CppUTest/TestFailure.h, src/CppUTest/SimpleString.cpp, src/CppUTest/TestFailure.cpp, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/TestFailureTest.cpp
When a string comparison (e.g. STRCMP_EQUAL) fails and the string contains non-printable characters (newlines, tabs, or even worse, ANSI color escape codes!) it's a mess to locate in the error log exactly where the comparison failed.
To avoid this, this PR makes cpputest replace non-printable characters with their corresponding C escape cores when printing the error log, making it easier to compare both strings.
=> Errors for string comparisons to show non-printable control characters as C escape codes

CMakeLists.txt
fix typo "exaples" to "examples"
=> fix typo "exaples" to "examples"

scripts/filterGcov.sh
If you filename contains "File" like ....configFile.c
The filter removes the whole file name minus ".c".
This inhibits the html output to access the coverage file.
=> filterGcov.sh fails if your filename or path contains "File"

src/Platforms/Gcc/UtestPlatform.cpp
There is a check for a clang version that is not guarded by a check if clang is defined. This MR adds this guard otherwise there is a compiler warning for compiling with g++ and -Wundef.
Fixes #1445
=> Add missing clang check

build/MakefileWorker.mk
The clang version check in build/MakefileWorker.mk only worked for apple
clang, so this changes the version checking to work with apple, debian,
and ubuntu clang version strings.
Additionally, clang 12 added -Wpoison-system-directories, which warns if
you if you include stuff from /usr/local/include when doing a cross
compile.
Apple clang thinks it's always doing a cross compile for some reason, so
that always complains.
Closes #1456
=> Fix clang version check and remove clang 12 warning

build/MakefileWorker.mk
Previously if your tests segfaulted, `make test` would return
successfully, and print a simple warning in white text mixed in with all
the other output.
This checks the return code from the test binary and prints a warning if
it's nonzero.
Closes #1443
=> make test shows test binary return codes

.github/workflows/codeql.yml
Adds a CodeQL build, based on Github Action. A weekly cron ensures checking with latest queries on a regular basis, even if there's no commit in the repo.
@basvodde With the current situation on Travis, what's your opinion on moving to GH Actions in general?
=> CodeQL Github Action

src/CppUTest/Utest.cpp, tests/CppUTest/MemoryOperatorOverloadTest.cpp
GCC 11 has introduced a set of new warnings. Since the behaviour they should prevent is used in tests explicitly, they need to be disabled – with minimal scope.
=> GCC 11 compatibility

CMakeLists.txt, configure.ac, src/Platforms/Gcc/UtestPlatform.cpp, tests/CppUTest/UtestPlatformTest.cpp, tests/CppUTest/UtestTest.cpp
I am doing some R&D regarding the bcc2 compiler from Gaisler and I wanted to use cpputest as a test library in the future.
While trying to build the library using that compiler, with STD_C `on`, I encountered a linker error - undefined reference to `waitpid`. After some debugging I found, that the library checks if the compiler provides `fork` function and if it does it uses platform specific fork and waitpid implementations (UtestPlatform.cpp:64). Apparently Gaisler uses a stub fork (among some others), but waitpid is missing:
To be able to compile the library in such situation I added an additional check - for waitpid availability. With this I am able to use cpputest with my project, and run tests using LEON3 simulator.
=> Fixed build using bcc2 compiler

index.html
github pages are now hosted under `.io` domain
( https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages )
=> redirect to github.io

src/CppUTest/SimpleString.cpp
the Borland compiler does not like the expression (*s1++ = *s2++) as part of a while condition,  This commit rewrites the while loop, moving the assignment out of the while test expression.
=> Update SimpleString.cpp for Borland compiler

include/CppUTest/CommandLineArguments.h, include/CppUTest/TestRegistry.h, src/CppUTest/CommandLineArguments.cpp, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/TestRegistry.cpp, tests/CppUTest/CommandLineTestRunnerTest.cpp, tests/CppUTest/TestRegistryTest.cpp
In the format of 
TestGroup.TestName.FileLocation.LineNumber\n
This is to close #1497
=> add -ll argument for retrieving test locations (file names and line numbers)

tests/CppUTest/MemoryLeakWarningTest.cpp, tests/CppUTest/SimpleStringCacheTest.cpp, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/TestHarness_cTest.cpp, tests/CppUTest/TestMemoryAllocatorTest.cpp, tests/CppUTest/TestUTestMacro.cpp, tests/CppUTest/TestUTestStringMacro.cpp, tests/CppUTest/UtestPlatformTest.cpp, tests/CppUTest/UtestTest.cpp, tests/CppUTestExt/GTest1Test.cpp, tests/CppUTestExt/IEEE754PluginTest.cpp, tests/CppUTestExt/MockFakeLongLong.cpp, tests/CppUTestExt/MockPluginTest.cpp
Clang 13 has become more strict on usage of reserved identifier.
=> Fix reserved identifier usage

.github/workflows/codeql.yml
The `checkout` step has switched to `main` as default branch. `master` still exists, but isn't updated anymore.
=> Update GH Action branch

src/CppUTest/CMakeLists.txt
By letting CMake handle the windows library suffix (.lib or .a)
_First contribution Hope requirements are met_
=> Fix compile gcc from cygwin

CMakeLists.txt
`src/Platforms/Gcc/UTestPlatform.cpp:38` relies on `CPPUTEST_HAVE_GETTIMEOFDAY` as an indicator that
`sys/time.h` will exist but that header is not present with TI-CGT-ARM despite the original test succeeding.
=> More reliable `gettimeofday` detection.

src/CppUTest/SimpleString.cpp
Borland 5.4 does not like (str = StrStr(str, substr.getBuffer())) in a while condition. This rewrites the while() moving the assignment out of the while condition
=> Update SimpleString.cpp for Borland 5.4 compiler

src/CppUTest/SimpleString.cpp
In the expression a? true : false;  True and False have to be the same type.  The Borland Compiler v5.4 is unable to automatically  promote the char array "(null)" to a SimpleString in this expression.
=> Required to  compile with Borland Compiler v5.4

src/CppUTest/SimpleString.cpp
In the expression a? true : false; True and False have to be the same type. The Borland Compiler v5.4 is unable to automatically promote the char array "(null)" to a SimpleString in this expression.
=> Required to compile with Borland Compiler v5.4 part4

src/CppUTest/SimpleString.cpp
In the expression a? true : false; True and False have to be the same type. The Borland Compiler v5.4 is unable to automatically promote the char array "(null)" to a SimpleString in this expression.
=> Required to compile with Borland Compiler v5.4 part5

src/CppUTest/SimpleString.cpp
In the expression a? true : false; True and False have to be the same type. The Borland Compiler v5.4 is unable to automatically promote the char array "(null)" to a SimpleString in this expression.
=> Required to compile with Borland Compiler v5.4 part6

src/CppUTest/TestMemoryAllocator.cpp
In the expression a? true : false; True and False have to be the same type. The Borland Compiler v5.4 is unable to automatically promote the char array "other" to a SimpleString in this expression.
Updating src/CppUTest/TestMemoryAllocator.cpp
=> Required to compile with Borland Compiler v5.4 part7

src/CppUTestExt/MockExpectedCall.cpp
In the expression a? true : false; True and False have to be the same type. The Borland Compiler v5.4 is unable to automatically promote the char array "" to a SimpleString in this expression.
Updating src/CppUTestExt/MockExpectedCall.cpp
=> Required to compile with Borland Compiler v5.4 part8

src/CppUTestExt/MockExpectedCall.cpp
In the expression a? true : false; True and False have to be the same type. The Borland Compiler v5.4 is unable to automatically promote the char array "failed" to a SimpleString in this expression.
Updating src/CppUTestExt/MockExpectedCall.cpp
=> Required to compile with Borland Compiler v5.4 part9

include/CppUTest/UtestMacros.h
long long is compiler specific and we already have a cpputest_longlong typedef that takes care of this for us.
=> cpputest_longlong for long long

include/CppUTest/UtestMacros.h
unsigned long long is compiler specific and we already have a cpputest_ulonglong typedef that takes care of this for us.
=> cpputest_ulonglong for unsigned long long

build/MakefileWorker.mk
This change allows a user to specify a compiler prefix such as `arm-none-eabi-`.
More importantly, this allows a developer to add the prefix `ccache ` to speed up testing.
=> Add CPPUTEST_CXX_PREFIX and CPPUTEST_CC_PREFIX to MakefileWorker.mk

build/MakefileWorker.mk
This allows the user to define MORE_SILENCE in the Makefile and get rid
of output like “compiling …”, “Building archive …”, etc. The idea is
that a successful test run should have minimal output.
This is a proposed implementation of the enhancement suggested in #1520.
=> Add option for less verbose output

src/Platforms/Borland/UtestPlatform.cpp
removed the first #ifdef __clang__  as this will never be called as this file will only be included when __clang__ is not defined.
=> The first of a number of changes to make this file a Borland specific file.

src/CppUTest/SimpleString.cpp
The usage of `NULL` causes warnings on some modern compiler.
=> Fix nullptr for modern compiler

include/CppUTest/CppUTestConfig.h, include/CppUTest/SimpleString.h
When compiling CppUTest with MinGW-w64 (tested with different versions from 8.x to 10.x) with long long support enabled, the following warning is thrown:
```
[build] C:\Work\cpputest\src\CppUTest\SimpleString.cpp: In function 'SimpleString StringFrom(cpputest_longlong)':
[build] C:\Work\cpputest\src\CppUTest\SimpleString.cpp:788:32: warning: unknown conversion type character 'l' in format [-Wformat=]
[build]   788 |     return StringFromFormat("%lld", value);
[build]       |                                ^
[build] C:\Work\cpputest\src\CppUTest\SimpleString.cpp:788:29: warning: too many arguments for format [-Wformat-extra-args]
[build]   788 |     return StringFromFormat("%lld", value);
[build]       |                             ^~~~~~
[build] …
```
=> Fix warning about wrong printf format when compiling with MinGW-w64

CMakeLists.txt, examples/AllTests/CMakeLists.txt, src/CppUTest/CMakeLists.txt, src/CppUTestExt/CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
Added options to CMake scripts for appending architecture size and debug indication to generated library names.
This way it is easier to deploy together both debug and release versions of the library, and 32/64 bits versions, avoiding headaches when trying to find out with which CppUTest library your are linking.
=> Library names indicating architecture size and debug

include/CppUTestExt/MockExpectedCallsList.h, include/CppUTestExt/MockFailure.h, src/CppUTestExt/MockActualCall.cpp, src/CppUTestExt/MockExpectedCallsList.cpp, src/CppUTestExt/MockFailure.cpp, tests/CppUTestExt/ExpectedFunctionsListTest.cpp, tests/CppUTestExt/MockComparatorCopierTest.cpp, tests/CppUTestExt/MockFailureTest.cpp, tests/CppUTestExt/MockHierarchyTest.cpp, tests/CppUTestExt/MockParameterTest.cpp
When CppUTest fails because an actual call matched partially one or more expected calls, but these have still parameters not fulfilled, the message shown is badly formatted and hard to understand.
For example, let's execute a test where a function with several overloads is mocked like the following one: 
``` C++
TEST( TestSuite, ExampleTest )
{
mock().expectOneCall("foo").withParameter("bar", 0);
mock().expectOneCall("foo").withParameter("bar", 5);
mock().expectOneCall("foo").withParameter("bar", 2).withParameter("boo", "blah");
mock().expectOneCall("foo").withParameter("bar", 2).withParameter("boo", "bleh");
mock().actualCall("foo").withParameter("bar", 0);
mock().actualCall("foo").withParameter("bar", 2); // < This call fails
// ... 
mock().checkExpectations();
}
```
The message that is …
=> Clarification of the message displayed when an actual call fails because of missing parameters

src/Platforms/Borland/UtestPlatform.cpp
Create std::nothrow constant
This will close #1546
and is part of #1493 (see https://github.com/cpputest/cpputest/issues/1493#issuecomment-948318023)
=> Update UtestPlatform.cpp for compiling with Borland 5.4 compiler

tests/CppUTest/TestFailureNaNTest.cpp
The Borland v5.4 compiler does not do NaN or Inf so we need to guard all the tests in this file with CPPUTEST_HAS_NAN == 1 && CPPUTEST_HAS_INF == 1
This will close #1544
and is part of #1493 (see https://github.com/cpputest/cpputest/issues/1493#issuecomment-948575510)
=> Update TestFailureNaNTest.cpp for compiling with Borland 5.4 compiler

build/MakefileWorker.mk
This is useful if comparing .gcda files generated during UT run to files built during normal build stage, rather than files built during UT
=> Add flag `CPPUTEST_USE_GCOV_NO_GCNO_FILES` to prevent .gcno files from being generated

src/Platforms/Borland/UtestPlatform.cpp
Adding a Borland specific VSNprintf function.
This closes https://github.com/cpputest/cpputest/issues/1556
and is part of https://github.com/cpputest/cpputest/issues/1493
=> Update UtestPlatform.cpp for compiling with Borland v5.4 compiler

include/CppUTest/CommandLineArguments.h, include/CppUTest/TestFailure.h, include/CppUTest/Utest.h, src/CppUTest/CommandLineArguments.cpp, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/TestFailure.cpp, src/CppUTest/Utest.cpp, tests/CppUTest/CommandLineArgumentsTest.cpp, tests/CppUTest/TestFailureTest.cpp, tests/CppUTest/UtestTest.cpp
This way when an unexpected exception is thrown it is handled as a test failure, so failure info is displayed, the remaining tests execution is not aborted, and in some platforms the OS does not display an error message or tries to launch a debugger.
=> Add support for generating a test failure when an unexpected exception is thrown

.github/workflows/basic.yml, .github/workflows/extended.yml
This gets at least some of the old travis builds running again using GitHub actions. There's still a bunch of follow on work we'll need to take on after this:
- C++98 support is broken because newer features have been introduced in TestFailure.cpp, CompatiblityTests.cpp, SimpleStringTest.cpp for example.
- The old version of GTest/GMock that travis used seems to depend on python2 which is EOL.
- DOSBox has trouble running in GitHub Actions' terminal.
- There are a bunch of other configs from travis that need to migrate too.
=> GitHub actions

include/CppUTest/TestPlugin.h
A complete type definition of `SimpleString` is needed for the
[`TestPlugin::name_`](https://github.com/cpputest/cpputest/pull/1595/files#diff-dcad8947c1a84d4452d86a21d72741888fced98bdd41055d74e7a665b757eac9L75) member.
=> Add missing include

tests/CppUTest/CommandLineTestRunnerTest.cpp
Since CppUTest can build without CppUTestExt, it we should be able to test without it as well.  This header was unreferenced.
=> Remove extensions from CppUTest tests

CMakeLists.txt
- When used as a subproject, don't assign `CMAKE_BUILD_CONFIG`. The default (i.e. empty) build type is valid and should not be overridden.
- Avoid setting a build type when using a [multi-configuration generator](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html) in which case there is not a single build config.
- Print a message so that users know that a default build type has been assigned implicitly.
=> Don't hijack the user's build config

build/MakefileWorker.mk, cmake/Modules/CppUTestWarningFlags.cmake, configure.ac
> Since `-Weverything` enables every diagnostic, we generally don’t
> recommend using it. `-Wall -Wextra` are a better choice for most projects.
> Using `-Weverything` means that updating your compiler is more difficult
> because you’re exposed to experimental diagnostics which might be of
> lower quality than the default ones.
https://clang.llvm.org/docs/UsersManual.html?highlight=weverything#diagnostics-enable-everything
=> Remove `-Weverything` flag

build/MakefileWorker.mk
Apple clang is different than normal clang for reasons.
We need to ignore some stuff specifically for apple clang.
I did some testing with https://github.com/sickcodes/Docker-OSX to
figure out what versions of apple clang need what warnings surpressed.
None of these warnings happen with normal clang.
```
10.15: "Catalina"
Apple clang version 11.0.3 (clang-1103.0.32.62)  Xcode_11.5
No extra warning suppression required
Apple clang version 12.0.0 (clang-1200.0.32.2)   Xcode_12
Apple clang version 12.0.0 (clang-1200.0.32.27)  Xcode_12.2
Apple clang version 12.0.0 (clang-1200.0.32.28)  Xcode_12.3
Apple clang version 12.0.0 (clang-1200.0.32.29)  Xcode_12.4
poison-system-directories
11: "Big Sur"
Apple clang version 12.0.5 (clang-1205.0.22.9)   Xcode_12.5
Apple clang version 12.0.5 …
```
=> Ignore apple clang warnings properly

tests/CppUTest/DummyMemoryLeakDetector.h, tests/CppUTestExt/IEEE754PluginTest.cpp, tests/CppUTestExt/IEEE754PluginTest_c.h
Extracts `extern "C"` to the header so consumers don't need to care and adds two missing include guards.
=> Extract 'extern C', add missing include guards

build/MakefileWorker.mk
When I made 7fc2a5e18e5567df67a135d6a7fe6311f92a9660 I stored the
return code from the test binary in a temp file and then deleted the
temp file.
But that temp file was created every time MakefileWorker.mk was sourced,
not just when the targets were run.
This commit changes it so the temp file is only created if the relevant
targets are being run so it will always get deleted.
=> stop creating temp files that aren't cleaned up

.github/workflows/extended.yml, CMakeLists.txt, cmake/arm-none-eabi-gcc.toolchain.cmake, examples/AllTests/CMakeLists.txt, src/Platforms/Gcc/UtestPlatform.cpp, tests/CppUTestExt/MockReturnValueTest.cpp
Test discovery depends on the ability to run the test executables on host. Without an emulator, there's no way to do that.
=> Disable test discovery when cross-compiling without an emulator

.github/workflows/extended.yml, CMakeLists.txt, tests/CppUTest/TestFailureNaNTest.cpp
=> Automatically disable C++ standard library usage when exceptions are disabled

.github/workflows/extended.yml
This is in line with behavior from before CI broke: https://coveralls.io/builds/44525666
=> Omit tests from coverage

include/CppUTest/PlatformSpecificFunctions_c.h, src/CppUTest/TestOutput.cpp, src/Platforms/Borland/UtestPlatform.cpp, src/Platforms/C2000/UtestPlatform.cpp, src/Platforms/Dos/UtestPlatform.cpp, src/Platforms/Gcc/UtestPlatform.cpp, src/Platforms/GccNoStdC/UtestPlatform.cpp, src/Platforms/Iar/UtestPlatform.cpp, src/Platforms/Keil/UtestPlatform.cpp, src/Platforms/Symbian/UtestPlatform.cpp, src/Platforms/VisualCpp/UtestPlatform.cpp, src/Platforms/armcc/UtestPlatform.cpp, tests/CppUTest/CommandLineTestRunnerTest.cpp
When semihosting, repeatedly calling `fputs` for each character drives very high syscall overhead.
Since this was the only use of `PlatformSpecificPutchar`, I've removed it entirely.
=> Switch from putchar to fputs

.github/workflows/basic.yml, CMakeLists.txt
`deleteWillNotThrowAnExceptionWhenDeletingUnallocatedMemoryButCanStillCauseTestFailures` hangs so I disabled memory leak detection.
=> Add Visual Studio Clang-CL build to CI

CMakeLists.txt, src/CppUTest/CMakeLists.txt, src/CppUTestExt/CMakeLists.txt
This duplicates the natively supported [`CMAKE_DEBUG_POSTFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_DEBUG_POSTFIX.html).
=> Remove `CPPUTEST_LIBNAME_POSTFIX_DEBUG`

examples/ApplicationLib/hello.c, include/CppUTest/TestHarness_c.h, tests/CppUTest/AllocationInCFile.c, tests/CppUTestExt/IEEE754PluginTest_c.c
Add missing `void`s to C functions.
=> Fix strict prototypes of Clang 15

cmake/Modules/CppUTestWarningFlags.cmake, examples/AllTests/AllTests.cpp, examples/AllTests/CircularBufferTest.cpp, examples/AllTests/EventDispatcherTest.cpp, examples/AllTests/FEDemoTest.cpp, examples/AllTests/HelloTest.cpp, examples/AllTests/MockDocumentationTest.cpp, examples/AllTests/MockPrinter.h, examples/AllTests/PrinterTest.cpp, include/CppUTestExt/MockCheckedActualCall.h
These raised warnings with [`-Wsuggest-override`](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-Wsuggest-override). I personally find this easier to read as well.
=> Resolve malformed override specifiers with function pointers

examples/AllTests/FEDemoTest.cpp
Remove deprecated usage of `volatile` in C++20.
=> Fix compilation on C++20

build/MakefileWorker.mk
`MakefileWorker.mk` assumes that all files in directories in `MOCKS_SRC_DIRS` should be included in the current test. A large project may build multiple tests that share some mocks. Using all files can result in mocks over-riding symbols that are part of the TARGET_LIB.
For example, consider a layout like:
```
├── mocks
│   ├── mock_bar.cpp
│   ├── mock_buzz.cpp
│   ├── mock_fizz.cpp
│   └── mock_foo.cpp
├── src
│   ├── bar.c
│   ├── buzz.c
│   ├── fizz.c
│   └── foo.c
└── tests
├── Makefile_bar.mk
├── Makefile_foo.mk
├── test_bar.cpp
└── test_foo.cpp
```
where all the `.c` files in `src` are built as a static library and depend on each other. `test_bar.cpp` depends on functions in `foo.c`, `buzz.c` and `fizz.c`. And `test_foo.cpp` depends on functions in `bar.c', 'buzz.c' and 'fizz.c`. …
=> Allow specifying individual mock sources with MOCK_SRC_FILES

CMakeLists.txt
This didn't actually work anyway; non-cache variables are scoped to the directory in which they are set. I think CMake support for memory leak detection needs some dedicated attention, but this at least avoids surprising users with unexpected flags and broken features.
=> Avoid trying to set downstream users' global flags.

include/CppUTest/UtestMacros.h
Improve performance of CHECK_COMPARE_LOCATION by moving comparison result check above the SimpleString instantiation.
Performance drop of the test suite will occur if CHECK_COMPARE_LOCATION() is called inside some tight loop which is checking many multiple variants of values. SimpleString instantiation and filling with error message takes time and in case of a large loop may block execution for a long time. Proposed improvement eliminates this problem while keeping logic of the check intact.
=> Improve performance of CHECK_COMPARE_LOCATION.

include/CppUTest/PlatformSpecificFunctions_c.h, src/Platforms/Borland/UtestPlatform.cpp, src/Platforms/C2000/UtestPlatform.cpp, src/Platforms/Dos/UtestPlatform.cpp, src/Platforms/Gcc/UtestPlatform.cpp, src/Platforms/GccNoStdC/UtestPlatform.cpp, src/Platforms/Iar/UtestPlatform.cpp, src/Platforms/Keil/UtestPlatform.cpp, src/Platforms/Symbian/UtestPlatform.cpp, src/Platforms/VisualCpp/UtestPlatform.cpp, src/Platforms/armcc/UtestPlatform.cpp
When putchar support was dropped by 80d807c1de79ee7307beae923ba2ad382bd17cd5 commit it became impossible to redirect log output to some arbitrary logging function without removing the `const` specifier of `PlatformSpecificStdOut`.
Consider the following usage example (pseudocode):
```cpp
static void LogRedirectorPuts(const char* str, PlatformSpecificFile file)
{
#ifdef _UTEST_IMMEDIATE_LOG
Log.Warning("%s", str);
#else
((std::string *)file)->append(str);
#endif
}
static void RunTests()
{
std::string log_buffer;
PlatformSpecificStdOut = &log_buffer;
PlatformSpecificFPuts  = LogRedirectorPuts;
char **tmp = NULL;
int result = RUN_ALL_TESTS(0, tmp);
if (result != 0)
{	
Log.ErrorSrc(TEST_LOG, "failure:\n--//--\n%s--//--", log_buffer.c_str());
}
else
{
Log.VerboseSrc(TEST_LOG, …
```
=> Allow redirection of PlatformSpecificStdOut.

cmake/Modules/CppUTestConfigurationOptions.cmake, src/CppUTest/CMakeLists.txt
Variables do not propagate outside a CMake project; settings have to be attached to targets. This moves the force include flags from the global variables (that never exit the project) to the `CppUTest::CppUTest` target so that anything that links to it will get the includes.
=> Fix leak detection with CMake

include/CppUTest/CppUTestConfig.h, include/CppUTest/TestHarness_c.h
- Keep `NULLPTR`, `_override`, and `_destructor_override` macros out of
C. We had some leak into TestHarness_c.h.
- Drop Green Hills workaround for `override` with function pointers added
in #1239. This was mitigated in #1605.
=> Keep C++98 compatibility macros out of C

.github/workflows/basic.yml, CMakeLists.txt, CMakePresets.json, cmake/Modules/CppUTestBuildTimeDiscoverTests.cmake, examples/AllTests/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
When `DETAILED` is passed to `cpputest_buildtime_discover_tests`, that value will take precedence over the `CPPUTEST_TESTS_DETAILED` variable.
For the following invocations:
```cmake
cpputest_buildtime_discover_tests(A)
cpputest_buildtime_discover_tests(B DETAILED TRUE)
cpputest_buildtime_discover_tests(C DETAILED FALSE)
```
- When `CPPUTEST_TESTS_DETAILED` is falsey, _B_ tests will be detailed.
- When `CPPUTEST_TESTS_DETAILED` is truthy, _A_ and _B_ tests will be detailed.
This is useful in cases like `TestOrderedTestMacros`, which fail when run in detailed-mode.
=> Allow detailed tests to be set at call site

src/CppUTest/TestFailure.cpp
This PR fixes regression introduced by 3756d31e09e039662ee81e4672634ba8d7b15bea by excluding `typeid()` RTTI function from the compilation if compiler settings did not enable RTTI support that is a fairly common case for Embedded development when C++ exceptions are enabled while RTTI not to balance between functionality and binary size.
=> Fixed compilation when exceptions are enabled but RTTI not.

include/CppUTest/CppUTestConfig.h, src/CppUTest/TestFailure.cpp
In response to #1670 cleans up the fix by moving RTTI detection into the config header.
=> Refactored RTTI feature detection and moved it to the config header.

CMakePresets.json, include/CppUTest/CppUTestConfig.h, src/CppUTest/SimpleString.cpp, tests/CppUTest/SimpleStringTest.cpp, tests/CppUTest/TestFailureTest.cpp, tests/CppUTest/TestUTestMacro.cpp
This change requires use-cases without the standard library to provide their appropriate byte size. Given the commitment to maintain support for use without standard C, I think we need to be more prudent about the assumptions we're making about those environments.
=> Don't guess CHAR_BIT

.github/workflows/basic.yml
Visual Studio is a multi-config generator. Though [test discovery currently ignores this](https://github.com/cpputest/cpputest/pull/1673), installation does not, so we need to pass the config type to the `cmake --install` command.
=> Test Windows install

tests/CppUTestExt/MockExpectedCallTest.cpp
This was unnecessary undefined behavior.
=> Don't cast away const

.github/workflows/basic.yml, include/CppUTest/CppUTestConfig.h, include/CppUTest/PlatformSpecificFunctions_c.h, src/CppUTest/Utest.cpp, src/Platforms/Borland/UtestPlatform.cpp, src/Platforms/C2000/UtestPlatform.cpp, src/Platforms/Dos/UtestPlatform.cpp, src/Platforms/Gcc/UtestPlatform.cpp, src/Platforms/GccNoStdC/UtestPlatform.cpp, src/Platforms/Iar/UtestPlatform.cpp, src/Platforms/Keil/UtestPlatform.cpp, src/Platforms/Symbian/UtestPlatform.cpp, src/Platforms/VisualCpp/UtestPlatform.cpp, src/Platforms/armcc/UtestPlatform.cpp, tests/CppUTest/UtestTest.cpp
This started hanging instead of crashing when built with Clang 14.0.6 on my box. Dereferencing a null pointer is not a valid or reliable way to induce a crash.
I also added back the no-std-c build which I guess got lost somewhere. This shook out a bug in my `CPPUTEST_CHAR_BIT` changes.
=> Call abort instead of invoking undefined behavior

.github/workflows/basic.yml, CMakeLists.txt, CMakePresets.json, include/CppUTest/CppUTestConfig.h, include/CppUTest/MemoryLeakDetectorNewMacros.h, include/CppUTest/TestFailure.h, include/CppUTest/UtestMacros.h, src/CppUTest/MemoryLeakWarningPlugin.cpp, src/CppUTest/TestFailure.cpp, src/CppUTest/Utest.cpp, tests/CppUTest/AllocationInCppFile.cpp, tests/CppUTest/AllocationInCppFile.h, tests/CppUTest/MemoryOperatorOverloadTest.cpp, tests/CppUTest/TestFailureTest.cpp, tests/CppUTest/TestUTestMacro.cpp, tests/CppUTest/UtestTest.cpp
Like RTTI, exceptions can be disabled independently of the C++ standard library. It is common to disable one or both of RTTI and exceptions while continuing to use remaining supported parts of the standard library in space- or time-constrained embedded systems.
=> Decouple C++ standard library and exception support

CMakeLists.txt, CMakePresets.json, include/CppUTest/StandardCLibrary.h, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt, tests/DummyUTestPlatform/DummyUTestPlatform.cpp
This gets the build without the C standard library under test by cheating at link time. None of CppUTest is built with libc (i.e. passing `-nostdinc`), but for testing we link to standard implementations of platform-specific functions.
Closes #1656
Closes #378
=> Test without C standard library

.github/workflows/basic.yml
This repairs CI. We may want to drop the QEMU test until v7 hits the Ubuntu repositories.  Otherwise we can expect this to break again.
=> Hotfix: Update QEMU URL

include/CppUTest/CppUTestConfig.h
6ee9aba75afa413bcd0e8089da71e6a8644ac177 started using` __STDC_IEC_559__`
to detect if IEC 60559 is supported, but with apple clang 14.0.0 it was
undefined and throwing -Wundef
This commit just adds a check for if it's defined before using it.
We use the MakefileWorker.mk interface
Full error:
```
In file included from /Users/user/projectDir/cpputest/include/CppUTest/MemoryLeakDetectorNewMacros.h:22:
/Users/user/projectDir/cpputest/include/CppUTest/CppUTestConfig.h:170:7: error: ‘__STDC_IEC_559__’ is not defined, evaluates to 0 [-Werror,-Wundef]
#if __STDC_IEC_559__ && CPPUTEST_USE_STD_C_LIB
^
1 error generated.
```
=> Don't error on OSX when __STDC_IEC_559__ isn't defined

src/CppUTest/CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
CppUTest itself depends on pthreads (when used), not just the tests.
=> Correct pthreads dependency

.github/workflows/basic.yml, tests/CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
I was trying to save map files from the ClangCL build to try to debug the hang in `BasicBehavior.deleteWillNotThrowAnExceptionWhenDeletingUnallocatedMemoryButCanStillCauseTestFailures`. Unfortunately ClangCL's linker (link-lld) can't generate map files (and neither can Mac's ld), but I figured it's worth saving them for the builds that can to make future errors easier to diagnose.
See saved map files listed under "Artifacts" here: https://github.com/cpputest/cpputest/actions/runs/3495321337.
Without a Windows system, I won't be able to pursue the problem with `BasicBehavior.deleteWillNotThrowAnExceptionWhenDeletingUnallocatedMemoryButCanStillCauseTestFailures` and ClangCL any further.
=> Save map files

src/CppUTest/TestFailure.cpp
If compiled without RTTI `e` is unused and issues a warning. Casting to void marks it as intentionally unused.
Should we create eg. an "unused()" for improved documentation (cast-to-void might not be known to everyone)?
=> Mark exception as unused

cmake/install.cmake
- `VERSION` is implied by the arguments to `project()`
- `CMakePackageConfigHelpers` is guaranteed to exist by the minimum CMake version (3.8)
=> Delete extraneous install configs

CMakeLists.txt, src/CppUTest/CMakeLists.txt, src/CppUTestExt/CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
These make the code very confusing and I cannot understand the use case. Multiple architectures cannot exist in the same CMake project. When installing, multiple architectures should probably be installed to different locations, not have different names. The native [`CMAKE_<CONFIG>_POSTFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_CONFIG_POSTFIX.html) variable can be used to append arbitrary suffixes to installed libraries.
This removes changes from #1538. I may not have all the context here. So I'd appreciate any insight @jgonzalezdr has on what this was originally intended to support.
=> Drop confusing *LibName variables

.github/workflows/basic.yml, Makefile.am
I am very skeptical of these results. I don't claim to understand autotools. Could you verify that this is exercising everything it should? I noticed some related code was commented out in:
- f5c2367ac28a8fa9f9148bbadc79d53284e80fd9
- b6899f75cffdae8c44d4689890bf6152c4a2b73a
=> Test with recent GTest versions

src/CppUTest/MemoryLeakWarningPlugin.cpp
=> Use the currently configured Test Terminator rather than a hard coded version

.gitignore, cpputest_build/.gitignore, scripts/appveyor_ci_build.ps1
I frequently delete the build directory when re-configuring builds and it creates very noisy git diffs, since the directory is currently tracked.
=> Delete build directory

.github/workflows/basic.yml, CMakePresets.json
Our workaround to download a new version on Ubuntu keeps breaking because the Debian URL is not stable.
- #1700
- #1738
=> Remove qemu from CI

CMakePresets.json
This should be more robust than the old .deb downloads.
=> Run QEMU with Docker

.github/workflows/basic.yml, CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
This borrows the strategy (and source lists) from the DOS Make build to split tests into smaller executables. This is prep for translating a 16-bit DOS build with CMake, but is also valuable for running tests on other small devices.
=> Allow for splitting test executables

.github/workflows/basic.yml, tests/CppUTest/MemoryOperatorOverloadTest.cpp
This is undefined behavior and has been failing very frequently on CI. The custom `delete` implementation calls `free()`.
> The behavior is undefined if after `free()` returns, an access is made through the pointer.
https://en.cppreference.com/w/c/memory/free
=> Remove undefined behavior

include/CppUTest/StandardCLibrary.h
I encountered the exact same issue as what was supposedly resolved in <https://github.com/cpputest/cpputest/pull/1192>, but for C++ code. What resolved it for me is adding `#include <cstring>` to `StandardCLibrary.h`.
Note that this appears to be a regression. <https://github.com/cpputest/cpputest/commit/8dded9ebc21d35c63c4258291e3fed3a35d74c98> is the last commit that builds without adding the extra header.
=> Fix conflicting declaration of cpputest_strdup_location

include/CppUTest/TestOutput.h, src/CppUTest/CommandLineTestRunner.cpp, src/CppUTest/TestOutput.cpp, tests/CppUTest/TestOutputTest.cpp
This PR fixes an empty console output when the "JUnit" and "very verbose" options are selected at the same time
=> support very verbose in CompositeTestOutput

CppUTest.vcxproj, tests/AllTests.vcxproj
Currently under Visual Studio, after building for a particular configuration/platform (x64/Release e.g.), switching to a different configuration, and then returning, compiling will rebuild the project although it was already built previously. This is due to the build script sharing directories for output files.
This change makes it so that each configuration has it's own build directory.
* "AllTests" and "CppUTest" projects now output intermediary files and output libraries in their respective configuration/platform directories which help the msvc build system determine which files need recompiling.
* Update build toolset
=> Updated MSVC project settings

include/CppUTest/TestHarness_c.h, src/CppUTest/TestHarness_c.cpp, tests/CppUTest/TestHarness_cTest.cpp
Currently there is no MEMCMP in the C harness.
So, new CHECK_EQUAL_C_MEMCMP macro could be useful in tests where we process binary data.
=> Add C version of MEMCMP_EQUAL

include/CppUTest/PlatformSpecificFunctions_c.h, src/Platforms/Borland/UtestPlatform.cpp, src/Platforms/C2000/UtestPlatform.cpp, src/Platforms/Dos/UtestPlatform.cpp, src/Platforms/Gcc/UtestPlatform.cpp, src/Platforms/GccNoStdC/UtestPlatform.cpp, src/Platforms/Iar/UtestPlatform.cpp, src/Platforms/Keil/UtestPlatform.cpp, src/Platforms/Symbian/UtestPlatform.cpp, src/Platforms/VisualCpp/UtestPlatform.cpp, src/Platforms/armcc/UtestPlatform.cpp, tests/CppUTest/JUnitOutputTest.cpp, tests/CppUTest/TeamCityOutputTest.cpp, tests/CppUTest/TestOutputTest.cpp, tests/CppUTest/TestResultTest.cpp, tests/DummyUTestPlatform/DummyUTestPlatform.cpp
Fixes https://github.com/cpputest/cpputest/issues/1762
Currently signed long int is used for storing current time in milliseconds (time is calculated by GetPlatformSpecificTimeInMillis()).
But on 32-bit platforms long could be a 32-bit number (e.g. C17 standard declares at 5.2.4.2.1 that long int should be at least 32 bits long).
Current unix timestamp in seconds is 31 bit long and timestamp in milliseconds is at least 41 bit long.
C/C++ standards declare that behavior of signed integer overflow is undefined (e.g. C17 example at 3.4.3).
The platform specific time is used only for calculating difference between end and start time. So, long could be replaced with unsigned long in that case without any negative effects.
=> Fix undefined behavior in case of time overflow on 32-bit platforms

CMakeLists.txt, tests/CppUTest/MemoryOperatorOverloadTest.cpp
This hangs in ClangCL.  Calling `delete` on a pointer that wasn't created by a `new` expression is undefined behavior.[1]  There are no valid assertions about post conditions here. Removing this test allows us to remove the hack added in #1641 and restore support for memory leak detection.
[1]: https://en.cppreference.com/w/cpp/language/delete.
=> Remove test of undefined behavior

include/CppUTest/CppUTestConfig.h
There is a warning in the `CppUTestConfig.h` on Linux platforms when building with ASAN. The warning says to disable memory leak detection in order to get rid of the warning with `-DCPPUTEST_MEM_LEAK_DETECTION_DISABLED`. However, providing said define does not get rid of the warning. This prevents compilation on Linux with ASAN + `-Werror`.
1. If `CPPUTEST_MEM_LEAK_DETECTION_DISABLED` do not display warning about address sanitization.
=> Suppress Sanitization Warning on Linux When Memory Leak Detection is Disabled

include/CppUTest/TestHarness_c.h
In PR https://github.com/cpputest/cpputest/pull/1773 NULLPTR was used as an argument CHECK_EQUAL_C_MEMCMP_LOCATION instead of NULL.
So, it was impossible to use CHECK_EQUAL_C_MEMCMP in C files.
=> Fix NULLPTR in C harness

include/CppUTest/StandardCLibrary.h
Replace `CPPUTEST_HAVE_STRING_H` with `CPPUTEST_HAVE_STRDUP` in `StandardCLibrary.h`
PR #1192 resolved a build issue related to projects including string.h for autoconf-based projects but not CMake-based projects. The autoconf projects have `CPPUTEST_HAVE_STRING_H` defined as part of `AC_CHECK_HEADERS` check for `string.h` but CMake projects do not have this same check.
The CMake projects *do* have a call to `check_cxx_symbol_exists` for `strdup` which is used to set `CPPUTEST_HAVE_STRDUP` in `config.h`. The autoconf project has the equivalent check via `AC_CHECK_FUNCS` for `strdup`, so gating the `string.h` inclusion in `StandardCLibrary.h` on `CPPUTEST_HAVE_STRDUP` is both functionally equivalent for autoconf projects and more precise.
Based on CppUTest git history, it seems like …
=> STRING_H: Gate string.h inclusion on STRDUP

include/CppUTest/CppUTestConfig.h
This causes issues with gcc < 5 and gmacros.h from glib >= 2.69.
The glib header thinks the compiler supports __has_attribute, so it uses it instead of doing version checks.
Then macros like G_GNUC_UNUSED become empty, as if no attribute was supported.
=> Do not define __has_attribute in a public header

tests/CppUTestExt/MockParameterTest.cpp
Fixes: https://github.com/cpputest/cpputest/issues/1801
=> MockParameterTest.cpp: fix ULL constants

build/MakefileWorker.mk, cmake/warnings.cmake, configure.ac, examples/AllTests/FEDemoTest.cpp, include/CppUTest/CppUTestConfig.h, src/Platforms/VisualCpp/UtestPlatform.cpp
We removed the last use of reserved macro names in #1800 and have a local suppression for the single keyword macro.
=> Remove excessive warning suppressions

src/CppUTest/JUnitTestOutput.cpp, tests/CppUTest/JUnitOutputTest.cpp
When calling the tests with `-ojunit` (Junit output), `\n` are replaced by `{newline}` which causes the Github Checks output to be inlined. 
This PR is replacing `\n` and `\r` by their encoded equivalent respectively `&#10;` and `&#13;`.
Now, when Jenkins reports the tests to Github Checks, the tests failures are readable.
What is the reason we are not replacing `\n` by `{newline}`? Should this instead be a Jenkins Junit plugin update to support `{newline}` or a post process from the user in the Jenkins pipeline?
Closes https://github.com/cpputest/cpputest/issues/1594
=> Encode newlines for -ojunit as their XML equivalent instead of {newline}

cmake/Modules/CppUTest.cmake
CMake 3.31 added a new warning for the added [CMP0175](https://cmake.org/cmake/help/latest/policy/CMP0175.html) policy which uncovered the previously ignored unused `DEPENDS` argument.
=> Resolve new CMake warning

CMakeLists.txt, examples/CMakeLists.txt, src/CppUTest/CMakeIntegration-README.md
Most recent CMake started complaining about the pending end of 3.8 support.
> ```
> CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
>   Compatibility with CMake < 3.10 will be removed from a future version of
>   CMake.
>
>   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
>   to tell CMake that the project requires at least <min> but has been updated
>   to work with policies introduced by <max> or earlier.
> ```
We can retain support by adding a max version. This will not prevent use with newer versions, but indicates forward compatibility.[^1]
[^1]: https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html
=> Squelch deprecation warning

.github/workflows/basic.yml
This PR fixes an issue for github repos that use cpputest as a submodule AND run workflows on github.
[Github has deprecated workflow "actions/upload-artifact@v3" "actions/download-artifact@v3"](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/). Unfortunately, github has a policy of scanning all ".github/workflows/*.yaml" files for deprecated actions, whether those workflows in submodules are run or not. The presence of deprecated actions causes a workflow error.
This PR bumps the actions version to v4.
=> Version bump of github workflow actions to v4.

README.md
dd70ae595cdd7374bd8e160e5d53fe9510904478 renamed TESTS to
CPPUTEST_BUILD_TESTING and defaulted it to off, so we no longer need to
set it to off in the example
=> update README.md fetchcontent cmake section remove test disable

src/CppUTest/Utest.cpp
work around spurious green hills error: `#811-D`
Same fix as #1628 addressing changes from #1430.
=> More GHS workarounds

CMakeLists.txt, cmake/Modules/CppUTest.cmake, examples/AllTests/CMakeLists.txt, tests/CppUTest/CMakeLists.txt, tests/CppUTestExt/CMakeLists.txt
Test discovery depends on being able to run the test executables. When cross compiling, that means using an emulator. There's no reason to try discovering tests when cross compiling without an emulator. This lets users (and us) avoid noisy guards at call sites in cross-platform projects.
I've added a warning for such cases so users get a useful explanation instead of the confusing errors that used to occur. (e.g. https://github.com/cpputest/cpputest/actions/runs/11062997988/job/30738413966?pr=1820#step:8:56)
=> Prevent attempts to discover cross compiled tests without an emulator

src/CppUTestExt/MockSupport.cpp, tests/CppUTestExt/MockCallTest.cpp
I want to check if all expected calls were called without failing test. `expectedCallsLeft`  returns true between `actualCall` and `checkExpectations`:
```c++
mock().expectedCallsLeft(); // false
mock().expectOneCall("boo");
mock().expectedCallsLeft()); //true
mock().actualCall("boo");
mock().expectedCallsLeft()); //TRUE BUT SHOULD BE FALSE
mock().checkExpectations();
mock().expectedCallsLeft()); //false
```
This PR fixes it by evaluating last actuall call inside `expectedCallsLeft`.
=> fix expectedCallsLeft after actual call

src/CppUTest/SimpleString.cpp, src/CppUTestExt/MockExpectedCall.cpp
`x` and `X` format specifiers are only defined for unsigned types.
https://en.cppreference.com/w/cpp/io/c/fprintf
=> Fix new ClangCL warnings

CMakeLists.txt, configure.ac
Leak detection requires modification of global state during allocation which GCC 15.1 now optimizes out by default[^1]:
> The `-fassume-sane-operators-new-delete` option has been added and enabled by default. This option allows control over some optimizations around calls to replaceable global operators new and delete. **If a program overrides those replaceable global operators and the replaced definitions read or modify global state visible to the rest of the program, programs might need to be compiled with `-fno-assume-sane-operators-new-delete`.**
This change detects GCC 15.1 and disables that optimization. The CMake build only affects the CppUTest project, not user builds. We have no way of injecting such a flag in users' projects.
Mitigates #1851.
[^1]: …
=> Change codegen for gcc 15.1+

.github/workflows/basic.yml, docker/Dockerfile.dos, scripts/dos_build_test.sh
Stop using a small part of travis_ci_build.sh
part of #1855
=> CI use one DOS script for docker/make workflows

include/CppUTestExt/MockSupport.h, include/CppUTestExt/MockSupport_c.h, src/CppUTestExt/MockSupport.cpp, src/CppUTestExt/MockSupport_c.cpp, tests/CppUTestExt/MockSupportTest.cpp, tests/CppUTestExt/MockSupport_cTest.cpp
For MockSupport getData functions, MockNamedValue and MockValue_c already support long int and unsigned long int.
However, there is no equivalent setData function that accepts these types. I have added support for long int and unsigned long int (in C++ and C), following the exact format and structure of the existing types.
Personally, this was useful when trying to pass a time_t as data to a mocked time() function, without running the risk of lossy typecasting / year 2038 problem.
=> Add support for long int and unsigned long int in Mock setData functions

.github/workflows/basic.yml, docker/Dockerfile.dos, docker/Dockerfile.ubuntu
qemu and buildx didn't do anything for these builds, and because these
aren't pushed or using private deps, authenticating to docker hub
doesn't do anything
related to #1855
=> ci: actually run docker builds

README.md
Please see [Integration as external CMake project](https://github.com/cpputest/cpputest?tab=readme-ov-file#integration-as-external-cmake-project) in the README.md.
The target, `example_test`, referenced in `target_link_libraries(example_test ...` , should match the target, `run_tests`, as defined in `add_executable(run_tests ...`.
Since `example_test` is used in other portions of the README.md, `run_tests` should be changed to `example_test` for parity and function.
=> Target name in README.md "Integration as external CMake project" should match.

README.md, src/CppUTest/CommandLineArguments.cpp
Add explanation for the run ignored tests cli argument.
I noticed that the -ri argument is in the print usage but not in the verbose help and I was not sure what this option did:
=> Document -ri CLI arg
